/**
 * =========================================================================
 * 日本大型電器城 (Bic Camera & Yodobashi) 全國門市模組
 * =========================================================================
 * 完整收錄 Bic Camera (ビックカメラ) 與 友都八喜 (ヨドバシカメラ)
 * 涵蓋全日本各大主要車站出口、觀光購物重鎮與旗艦百貨。
 */

import { findNearestStation } from '../core/geo.js';
import { validateSpotsBatch } from '../core/validator.js';
import { deduplicateSpots } from '../core/dedupe.js';

export const BIC_CAMERA_SEED = [
  // --- 東京首都圈 ---
  {
    code: 'bic-yurakucho',
    name: 'Bic Camera 有樂町旗艦店',
    nameJa: 'ビックカメラ 有楽町店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都千代田区有楽町1-11-1',
    lat: 35.6751,
    lng: 139.7634,
    phone: '03-5221-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop014.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', '銀座商圈', '旗艦館', '直通車站'],
    notes: 'JR 有樂町站日比谷口直通，B2 至 7 樓全日本指標性旗艦店，中文退稅專櫃、美妝、相機、生活家電、手錶一應俱全。'
  },
  {
    code: 'bic-ikebukuro-honten',
    name: 'Bic Camera 池袋本店',
    nameJa: 'ビックカメラ 池袋本店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都豊島区東池袋1-41-5',
    lat: 35.7315,
    lng: 139.7126,
    phone: '03-5396-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop007.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', '池袋商圈', '發祥總店'],
    notes: 'JR 池袋站東口出站即達，B1 至 8 樓大型旗艦總店，動漫、遊戲、3C 電腦、家電最齊全。'
  },
  {
    code: 'bic-ikebukuro-west',
    name: 'Bic Camera 池袋西口店',
    nameJa: 'ビックカメラ 池袋西口店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都豊島区西池袋1-16-3',
    lat: 35.7303,
    lng: 139.7093,
    phone: '03-5960-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop017.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', '池袋商圈', '車站步行1分內'],
    notes: '池袋站西口地下街出口直結，主打相機、手機、影音配件與退稅專區。'
  },
  {
    code: 'bic-shinjuku-east',
    name: 'Bic Camera 新宿東口店',
    nameJa: 'ビックカメラ 新宿東口店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都新宿区新宿3-29-1',
    lat: 35.6908,
    lng: 139.7032,
    phone: '03-3226-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop116.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', '新宿商圈', '地下街直通'],
    notes: '原 Bicqlo 旗艦大樓，新宿三丁目與新宿東口地下通道直結，全館各樓層免稅退稅，品項海量。'
  },
  {
    code: 'bic-shinjuku-west',
    name: 'Bic Camera 新宿西口店',
    nameJa: 'ビックカメラ 新宿西口店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都新宿区西新宿1-5-1 小田急ハルク',
    lat: 35.6923,
    lng: 139.6991,
    phone: '03-5326-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop016.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', '小田急HALC', '車站直通'],
    notes: 'JR 新宿站西口小田急 HALC 百貨 2 至 7 樓，交通樞紐最便利電器購物站。'
  },
  {
    code: 'bic-shinjuku-pepe',
    name: 'Bic Camera 西武新宿PePe店',
    nameJa: 'ビックカメラ 西武新宿PePe店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都新宿区歌舞伎町1-30-1 西武新宿PePe 6F-8F',
    lat: 35.6948,
    lng: 139.7009,
    phone: '03-5155-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop122.jsp',
    tags: ['免稅 (Tax-Free)', '出示折價券', '歌舞伎町旁', '西武新宿直結'],
    notes: '西武新宿站直結 PePe 百貨高樓層，營業至晚間，採購免稅家電便利。'
  },
  {
    code: 'bic-shibuya-east',
    name: 'Bic Camera 澀谷東口店',
    nameJa: 'ビックカメラ 渋谷東口店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都渋谷区渋谷1-24-12',
    lat: 35.6599,
    lng: 139.7028,
    phone: '03-5466-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop008.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', '澀谷商圈', '宮下公園旁'],
    notes: '澀谷宮下公園 MIYASHITA PARK 與澀谷站宮益坂口旁，潮流電器與美妝齊備。'
  },
  {
    code: 'bic-shibuya-hachiko',
    name: 'Bic Camera 澀谷八公口店',
    nameJa: 'ビックカメラ 渋谷ハチ公口店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都渋谷区道玄坂2-5-9',
    lat: 35.6593,
    lng: 139.6997,
    phone: '03-3477-0002',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop044.jsp',
    tags: ['免稅 (Tax-Free)', '出示折價券', '澀谷十字路口旁', '車站步行2分內'],
    notes: '澀谷十字路口八公犬方向，道玄坂入口超便利位置。'
  },
  {
    code: 'bic-akiba',
    name: 'Bic Camera AKIBA秋葉原店',
    nameJa: 'ビックカメラ AKIBA',
    region: '關東',
    prefecture: '東京都',
    address: '東京都千代田区外神田4-1-1',
    lat: 35.6998,
    lng: 139.7711,
    phone: '03-6260-8111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop121.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', '秋葉原電氣街', '動漫遊戲'],
    notes: '秋葉原中央通指標門市，全館 1 至 7 樓，相機、電競、模型公仔與免稅伴手禮。'
  },
  {
    code: 'bic-akasaka',
    name: 'Bic Camera 赤坂見附站店',
    nameJa: 'ビックカメラ 赤坂見附駅店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都港区赤坂3-1-6',
    lat: 35.6766,
    lng: 139.7369,
    phone: '03-6230-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop117.jsp',
    tags: ['免稅 (Tax-Free)', '出示折價券', '地鐵站直通', '商務客首選'],
    notes: '丸之內線與銀座線赤坂見附站直接出站即抵達，生活家電、美妝與酒類免稅。'
  },
  {
    code: 'bic-tachikawa',
    name: 'Bic Camera 立川店',
    nameJa: 'ビックカメラ 立川店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都立川市曙町2-12-2',
    lat: 35.6988,
    lng: 139.4144,
    phone: '042-548-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop040.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', '立川站北口直結'],
    notes: 'JR 立川站北口天橋直結，多摩地區最大型電器百貨。'
  },
  {
    code: 'bic-hachioji',
    name: 'Bic Camera 八王子店',
    nameJa: 'ビックカメラ 八王子店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都八王子市旭町1-17 セレオ八王子南館',
    lat: 35.6548,
    lng: 139.3385,
    phone: '042-646-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop109.jsp',
    tags: ['免稅 (Tax-Free)', '出示折價券', 'CELEO八王子南館直通'],
    notes: 'JR 八王子站南館直結，全館 1 至 5 樓大型電器量販。'
  },
  {
    code: 'bic-machida',
    name: 'Bic Camera 町田店',
    nameJa: 'ビックカメラ 町田店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都町田市原町田6-12-20 小田急百貨店町田店 7F-8F',
    lat: 35.5434,
    lng: 139.4452,
    phone: '042-794-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop125.jsp',
    tags: ['免稅 (Tax-Free)', '出示折價券', '小田急百貨直通'],
    notes: '小田急町田站直通百貨高樓層，相機、3C 與日常家電。'
  },
  {
    code: 'bic-air-haneda',
    name: 'Air BIC CAMERA 羽田機場第3航廈店',
    nameJa: 'Air BIC CAMERA 羽田空港第3ターミナル店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都大田区羽田空港2-6-5 羽田空港第3旅客ターミナル 2F',
    lat: 35.5494,
    lng: 139.7798,
    phone: '03-5579-7565',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop402.jsp',
    tags: ['免稅 (Tax-Free)', '機場免稅店', '出示折價券', '羽田國際線'],
    notes: '羽田機場國際線出境/入境大廳，熱門美容儀器、保溫杯、耳機與伴手禮。'
  },
  {
    code: 'bic-air-narita-t2',
    name: 'Air BIC CAMERA 成田機場第2航廈店',
    nameJa: 'Air BIC CAMERA 成田空港第2ターミナル店',
    region: '關東',
    prefecture: '千葉縣',
    address: '千葉県成田市古込字込前1-1 成田空港第2旅客ターミナル 4F',
    lat: 35.7725,
    lng: 140.3929,
    phone: '0476-34-8031',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop401.jsp',
    tags: ['免稅 (Tax-Free)', '機場免稅店', '出示折價券', '成田國際線'],
    notes: '成田機場第 2 航廈出境前商城 4 樓，最後採購日本電器與旅行用品首選。'
  },
  {
    code: 'bic-yokohama-west',
    name: 'Bic Camera 橫濱西口店',
    nameJa: 'ビックカメラ 横浜西口店',
    region: '關東',
    prefecture: '神奈川縣',
    address: '神奈川県横浜市西区南幸2-1-29',
    lat: 35.4655,
    lng: 139.6192,
    phone: '045-320-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop005.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', '橫濱站商圈'],
    notes: '橫濱站西口相鐵出口步行 2 分鐘，全館 1 至 6 樓電器城。'
  },
  {
    code: 'bic-shin-yokohama',
    name: 'Bic Camera 新橫濱店',
    nameJa: 'ビックカメラ 新横浜店',
    region: '關東',
    prefecture: '神奈川縣',
    address: '神奈川県横浜市港北区新横浜2-100-45 キュービックプラザ新横浜 3F-9F',
    lat: 35.5074,
    lng: 139.6178,
    phone: '045-478-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop037.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', '新幹線新橫濱直通'],
    notes: '新幹線新橫濱站共構 Cubic Plaza 3 至 9 樓，搭乘新幹線前後採買極為方便。'
  },
  {
    code: 'bic-kawasaki-lazona',
    name: 'Bic Camera Lazona川崎店',
    nameJa: 'ビックカメラ ラゾーナ川崎店',
    region: '關東',
    prefecture: '神奈川縣',
    address: '神奈川県川崎市幸区堀川町72-1 ラゾーナ川崎プラザ 1F-4F',
    lat: 35.5328,
    lng: 139.6965,
    phone: '044-520-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop038.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', '川崎站直通', 'Lazona商場'],
    notes: 'JR 川崎站西口直通 Lazona 大型購物中心 1 至 4 樓，規模宏大。'
  },
  {
    code: 'bic-omiya-sogo',
    name: 'Bic Camera 大宮西口SOGO店',
    nameJa: 'ビックカメラ 大宮西口そごう店',
    region: '關東',
    prefecture: '埼玉縣',
    address: '埼玉県さいたま市大宮区桜木町1-6-2 そごう大宮店 パーキング館',
    lat: 35.9056,
    lng: 139.6225,
    phone: '048-647-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop024.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', '大宮站西口直結'],
    notes: 'JR 大宮站西口天橋直結 SOGO 大宮店，全埼玉交通樞紐大型旗艦。'
  },
  {
    code: 'bic-kashiwa',
    name: 'Bic Camera 柏店',
    nameJa: 'ビックカメラ 柏店',
    region: '關東',
    prefecture: '千葉縣',
    address: '千葉県柏市柏1-1-20 ファミリかしわ',
    lat: 35.8622,
    lng: 139.9715,
    phone: '04-7165-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop020.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', '柏站東口直結'],
    notes: 'JR 與東武柏站東口直通，千葉常磐線最大型電器量販。'
  },
  {
    code: 'bic-funabashi-tobu',
    name: 'Bic Camera 船橋東武店',
    nameJa: 'ビックカメラ 船橋東武店',
    region: '關東',
    prefecture: '千葉縣',
    address: '千葉県船橋市本町7-1-1 東武百貨店船橋店 2F-3F',
    lat: 35.7018,
    lng: 139.9852,
    phone: '047-420-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop123.jsp',
    tags: ['免稅 (Tax-Free)', '出示折價券', '船橋站直通', '東武百貨內'],
    notes: 'JR 船橋站直結東武百貨，免稅退稅專櫃齊全。'
  },
  {
    code: 'bic-mito',
    name: 'Bic Camera 水戶站店',
    nameJa: 'ビックカメラ 水戸駅店',
    region: '關東',
    prefecture: '茨城縣',
    address: '茨城県水戸市宮町1-7-31 エクセルみなみ 4F-5F',
    lat: 36.3702,
    lng: 140.4765,
    phone: '029-303-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop115.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', '水戶站南口直結'],
    notes: 'JR 水戶站南口 Excel Minami 4 至 5 樓直結，茨城縣唯一大型 Bic Camera 旗艦。'
  },
  {
    code: 'bic-takasaki',
    name: 'Bic Camera 高崎東口店',
    nameJa: 'ビックカメラ 高崎東口店',
    region: '關東',
    prefecture: '群馬縣',
    address: '群馬県高崎市栄町1-1',
    lat: 36.3218,
    lng: 139.0142,
    phone: '027-321-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop002.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', '高崎站東口直結'],
    notes: '北陸/上越新幹線高崎站東口出站直達，發祥歷史悠久之大型量販店。'
  },
  {
    code: 'bic-sagamiono',
    name: 'Bic Camera 相模大野站店',
    nameJa: 'ビックカメラ 相模大野駅店',
    region: '關東',
    prefecture: '神奈川縣',
    address: '神奈川県相模原市南区相模大野3-8-1 相模大野ステーションスクエア B館 6F',
    lat: 35.5315,
    lng: 139.4372,
    phone: '042-701-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop114.jsp',
    tags: ['免稅 (Tax-Free)', '出示折價券', '小田急相模大野直通'],
    notes: '小田急相模大野站共構商場 6 樓，生活家電與 3C 數位齊全。'
  },
  {
    code: 'bic-tamaplaza',
    name: 'Bic Camera Tama Plaza店',
    nameJa: 'ビックカメラ イトーヨーカドーたまプラーザ店',
    region: '關東',
    prefecture: '神奈川縣',
    address: '神奈川県横浜市青葉区美しが丘1-6-1 イトーヨーカドーたまプラーザ店 3F',
    lat: 35.5788,
    lng: 139.5582,
    phone: '045-909-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop126.jsp',
    tags: ['免稅 (Tax-Free)', '出示折價券', '東急たまプラーザ站旁'],
    notes: '東急田園都市線 Tama Plaza 站步行 2 分鐘，高質感生活家電專門。'
  },
  {
    code: 'bic-tokorozawa',
    name: 'Bic Camera 所澤站店',
    nameJa: 'ビックカメラ 所沢駅店',
    region: '關東',
    prefecture: '埼玉縣',
    address: '埼玉県所沢市くすのき台1-14-5 西武所沢S.C. 6F',
    lat: 35.7865,
    lng: 139.4735,
    phone: '04-2903-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop127.jsp',
    tags: ['免稅 (Tax-Free)', '出示折價券', '所澤站東口直結'],
    notes: '西武所澤站東口直通西武所澤 S.C. 6 樓，埼玉南部大型電器專門。'
  },

  // --- 近畿關西圈 (大阪 / 京都) ---
  {
    code: 'bic-namba',
    name: 'Bic Camera 難波店',
    nameJa: 'ビックカメラ なんば店',
    region: '近畿',
    prefecture: '大阪府',
    address: '大阪府大阪市中央区千日前2-10-1',
    lat: 34.6663,
    lng: 135.5032,
    phone: '06-6634-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop013.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', '道頓堀千日前', '關西旗艦館'],
    notes: '座落於千日前商圈與道頓堀旁，地下 1 樓至地上 7 樓關西超大型旗艦店，外國觀光客退稅服務最完善。'
  },
  {
    code: 'bic-kyoto-station',
    name: 'Bic Camera JR京都站店',
    nameJa: 'ビックカメラ JR京都駅店',
    region: '近畿',
    prefecture: '京都府',
    address: '京都府京都市下京区東塩小路町927 JR京都駅西口直結',
    lat: 34.9858,
    lng: 135.7562,
    phone: '075-353-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop035.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', 'JR京都站直通', '山陰線月台直達'],
    notes: 'JR 京都站 30 號月台直通，1 至 7 樓京都核心免稅電器據點。'
  },
  {
    code: 'bic-abeno-qs',
    name: 'Bic Camera 阿倍野 Q\'s Mall店',
    nameJa: 'ビックカメラ あべのキューズモール店',
    region: '近畿',
    prefecture: '大阪府',
    address: '大阪府大阪市阿倍野区阿倍野筋1-6-1 あべのキューズモール 3F',
    lat: 34.6468,
    lng: 135.5098,
    phone: '06-6631-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop118.jsp',
    tags: ['免稅 (Tax-Free)', '出示折價券', '天王寺阿倍野', '大型購物中心'],
    notes: '天王寺站阿倍野 Harukas 旁 Q\'s Mall 3 樓，南大阪家庭與遊客核心店。'
  },
  {
    code: 'bic-air-kansai-t1',
    name: 'Air BIC CAMERA 關西國際機場店',
    nameJa: 'Air BIC CAMERA 関西国際空港第1ターミナル店',
    region: '近畿',
    prefecture: '大阪府',
    address: '大阪府泉佐野市泉州空港北1番地 関西国際空港第1ターミナル 3F',
    lat: 34.4347,
    lng: 135.2442,
    phone: '072-456-6511',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop403.jsp',
    tags: ['免稅 (Tax-Free)', '機場免稅店', '出示折價券', '關西機場出境'],
    notes: '關西國際機場第 1 航廈 3 樓，登機前免稅採購專區。'
  },

  // --- 中部 / 東海 (名古屋 / 靜岡) ---
  {
    code: 'bic-nagoya-west',
    name: 'Bic Camera 名古屋站西店',
    nameJa: 'ビックカメラ 名古屋駅西店',
    region: '中部',
    prefecture: '愛知縣',
    address: '愛知県名古屋市中村区椿町6-9',
    lat: 35.1704,
    lng: 136.8804,
    phone: '052-459-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop033.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', '名古屋站太閤通口'],
    notes: 'JR 名古屋站太閤通口（新幹線口）出站即達，地下 1 樓至地上 5 樓電器城。'
  },
  {
    code: 'bic-nagoya-gate-tower',
    name: 'Bic Camera 名古屋JR Gate Tower店',
    nameJa: 'ビックカメラ 名古屋JRゲートタワー店',
    region: '中部',
    prefecture: '愛知縣',
    address: '愛知県名古屋市中村区名駅1-1-3 JRゲートタワー 9F-10F',
    lat: 35.1718,
    lng: 136.8828,
    phone: '052-569-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop120.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', 'JR Gate Tower', '最新旗艦'],
    notes: 'JR 名古屋站直通 Gate Tower 9 至 10 樓，全中部最新旗艦店，體驗型展示豐富。'
  },
  {
    code: 'bic-hamamatsu',
    name: 'Bic Camera 濱松店',
    nameJa: 'ビックカメラ 浜松店',
    region: '中部',
    prefecture: '靜岡縣',
    address: '静岡県浜松市中区砂山町322-1 プレスタワー / 遠鉄百貨店新館',
    lat: 34.7042,
    lng: 137.7345,
    phone: '053-455-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop042.jsp',
    tags: ['免稅 (Tax-Free)', '出示折價券', '濱松站前直通'],
    notes: 'JR 濱松站前遠鐵百貨新館，靜岡西部最大電器百貨。'
  },
  {
    code: 'bic-shizuoka',
    name: 'Bic Camera 靜岡Parche店',
    nameJa: 'ビックカメラ 静岡パルシェ店',
    region: '中部',
    prefecture: '靜岡縣',
    address: '静岡県静岡市葵区黒金町49 パルシェ 5F',
    lat: 34.9715,
    lng: 138.3892,
    phone: '054-205-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop128.jsp',
    tags: ['免稅 (Tax-Free)', '出示折價券', 'JR靜岡站直通', 'PARCHE百貨'],
    notes: 'JR 靜岡站共構 PARCHE 百貨 5 樓，新幹線與在來線出站即達。'
  },
  {
    code: 'bic-niigata',
    name: 'Bic Camera 新潟店',
    nameJa: 'ビックカメラ 新潟店',
    region: '中部',
    prefecture: '新潟縣',
    address: '新潟県新潟市中央区花園1-1-21 CoCoLo新潟 2F',
    lat: 37.9122,
    lng: 139.0615,
    phone: '025-248-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop031.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', 'JR新潟站直通', 'CoCoLo新潟'],
    notes: '上越新幹線新潟站共構 CoCoLo 新潟 2 樓，全新潟最具規模之免稅電器旗艦。'
  },

  // --- 北海道 / 東北 ---
  {
    code: 'bic-sapporo',
    name: 'Bic Camera 札幌店',
    nameJa: 'ビックカメラ 札幌店',
    region: '北海道・東北',
    prefecture: '北海道',
    address: '北海道札幌市中央区北4条西2丁目1 東急百貨店さっぽろ店 5F-6F',
    lat: 43.0673,
    lng: 141.3534,
    phone: '011-261-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop015.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', '札幌站南口', '東急百貨內'],
    notes: '札幌站南口東急百貨店 5 至 6 樓，北海道核心電器免稅重鎮。'
  },
  {
    code: 'bic-sendai',
    name: 'Bic Camera 仙台站西口店',
    nameJa: 'ビックカメラ 仙台駅西口店',
    region: '北海道・東北',
    prefecture: '宮城縣',
    address: '宮城県仙台市青葉区中央4-1-1',
    lat: 38.2588,
    lng: 140.8805,
    phone: '022-726-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop030.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', '仙台站西口直達'],
    notes: 'JR 仙台站西口天橋直結，東北最大型 Bic Camera 旗艦店。'
  },

  // --- 中國 / 四國 ---
  {
    code: 'bic-okayama',
    name: 'Bic Camera 岡山站前店',
    nameJa: 'ビックカメラ 岡山駅前店',
    region: '中國・四國',
    prefecture: '岡山縣',
    address: '岡山県岡山市北区駅前町1-1-1',
    lat: 34.6658,
    lng: 133.9195,
    phone: '086-236-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop036.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', '岡山站東口直結'],
    notes: 'JR 岡山站東口廣場正前方，地下街直接相連，全岡山最具規模電器店。'
  },
  {
    code: 'bic-hiroshima',
    name: 'Bic Camera 廣島站前店',
    nameJa: 'ビックカメラ 広島駅前店',
    region: '中國・四國',
    prefecture: '廣島縣',
    address: '広島県広島市南区松原町5-1 BIG FRONTひろしま B2F-3F',
    lat: 34.3971,
    lng: 132.4745,
    phone: '082-506-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop119.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', '廣島站南口直通', 'BIG FRONT'],
    notes: 'JR 廣島站南口地下道直結 BIG FRONT 廣島，全中國地區最新旗艦店。'
  },

  // --- 九州 / 沖繩 ---
  {
    code: 'bic-tenjin-1',
    name: 'Bic Camera 天神1號館',
    nameJa: 'ビックカメラ 天神1号館',
    region: '九州・沖繩',
    prefecture: '福岡縣',
    address: '福岡県福岡市中央区今泉1-25-1',
    lat: 33.5878,
    lng: 130.3995,
    phone: '092-732-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop018.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', '天神商圈', '西鐵福岡站旁'],
    notes: '西鐵福岡（天神）站南口出站即達，A/B 兩棟相連，主打手機、數位相機、筆電與免稅品。'
  },
  {
    code: 'bic-tenjin-2',
    name: 'Bic Camera 天神2號館',
    nameJa: 'ビックカメラ 天神2号館',
    region: '九州・沖繩',
    prefecture: '福岡縣',
    address: '福岡県福岡市中央区天神2-4-5',
    lat: 33.5888,
    lng: 130.3988,
    phone: '092-732-1112',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop023.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', '天神商圈', '生活家電'],
    notes: '天神新川通旁，地下 1 樓至地上 6 樓，生活家電、美妝儀器、藥妝與酒類最齊全。'
  },
  {
    code: 'bic-kumamoto',
    name: 'Bic Camera Amu Plaza熊本店',
    nameJa: 'ビックカメラ アミュプラザくまもと店',
    region: '九州・沖繩',
    prefecture: '熊本縣',
    address: '熊本県熊本市西区春日3-15-26 アミュプラザくまもと 2F',
    lat: 32.7895,
    lng: 130.6888,
    phone: '096-353-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop124.jsp',
    tags: ['免稅 (Tax-Free)', '出示折價券', '熊本站直通', 'Amu Plaza'],
    notes: 'JR 熊本站共構 Amu Plaza 2 樓，九州新幹線樞紐核心免稅店。'
  },
  {
    code: 'bic-kagoshima',
    name: 'Bic Camera 鹿兒島中央站店',
    nameJa: 'ビックカメラ 鹿児島中央駅店',
    region: '九州・沖繩',
    prefecture: '鹿兒島縣',
    address: '鹿児島県鹿児島市中央町1-1 えきマチ1丁目鹿児島',
    lat: 31.5835,
    lng: 130.5428,
    phone: '099-814-1111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop039.jsp',
    tags: ['免稅 (Tax-Free)', '出示折價券', '鹿兒島中央站直通'],
    notes: '九州新幹線鹿兒島中央站直結商場，南九州旗艦門市。'
  },
  {
    code: 'bic-air-naha',
    name: 'Air BIC CAMERA 那霸機場店',
    nameJa: 'Air BIC CAMERA 那覇空港店',
    region: '九州・沖繩',
    prefecture: '沖繩縣',
    address: '沖縄県那覇市鏡水150 那覇空港 国際線エリア 2F',
    lat: 26.2064,
    lng: 127.6465,
    phone: '098-891-8111',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop404.jsp',
    tags: ['免稅 (Tax-Free)', '機場免稅店', '出示折價券', '那霸國際線'],
    notes: '那霸機場國際線航廈出境區，沖繩返程免稅電器最後採買點。'
  },
  {
    code: 'bic-koji-rycom',
    name: 'Bic Camera / Kojima 沖繩來客夢店',
    nameJa: 'コジマ×ビックカメラ イオンモール沖縄ライカム店',
    region: '九州・沖繩',
    prefecture: '沖繩縣',
    address: '沖縄県中頭郡北中城村ライカム1番地 イオンモール沖縄ライカム 1F',
    lat: 26.3142,
    lng: 127.7958,
    phone: '098-931-1500',
    url: 'https://www.biccamera.com/bc/i/shop/shoplist/shop601.jsp',
    tags: ['免稅 (Tax-Free)', '大型電器城', '出示折價券', '永旺來客夢', '自駕必訪'],
    notes: '沖繩最大型購物中心永旺夢樂城來客夢 1 樓，全沖繩面積最廣電器城。'
  }
];

export const YODOBASHI_SEED = [
  // --- 東京首都圈 ---
  {
    code: 'yodobashi-akiba',
    name: '友都八喜 Multimedia Akiba旗艦店',
    nameJa: 'ヨドバシカメラ マルチメディアAkiba',
    region: '關東',
    prefecture: '東京都',
    address: '東京都千代田区神田花岡町1-1',
    lat: 35.6989,
    lng: 139.7747,
    phone: '03-5209-1010',
    url: 'https://www.yodobashi.com/ec/store/0018/index.html',
    tags: ['免稅 (Tax-Free)', '大型電器城', '日本最大旗艦店', '秋葉原站直結', '美食街', '退稅專屬通道'],
    notes: '全日本最知名、面積最大的電器旗艦百貨！1 至 6 樓電器 3C、相機、手錶與玩具，7 樓書店，8 樓美食餐廳街，營業至 22:00。'
  },
  {
    code: 'yodobashi-shinjuku-west',
    name: '友都八喜 新宿西口本店',
    nameJa: 'ヨドバシカメラ 新宿西口本店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都新宿区西新宿1-11-1',
    lat: 35.6905,
    lng: 139.6984,
    phone: '03-3346-1010',
    url: 'https://www.yodobashi.com/ec/store/0011/index.html',
    tags: ['免稅 (Tax-Free)', '大型電器城', '發祥總店', '新宿站西口', '多棟專門館'],
    notes: '友都八喜誕生之發祥總店，由相機館、電腦館、鐘錶綜合館、電視館等 6 棟大樓組成，專業度極高。'
  },
  {
    code: 'yodobashi-shinjuku-east',
    name: '友都八喜 Multimedia新宿東口店',
    nameJa: 'ヨドバシカメラ マルチメディア新宿東口',
    region: '關東',
    prefecture: '東京都',
    address: '東京都新宿区新宿3-26-7',
    lat: 35.6912,
    lng: 139.7018,
    phone: '03-3356-1010',
    url: 'https://www.yodobashi.com/ec/store/0013/index.html',
    tags: ['免稅 (Tax-Free)', '大型電器城', '新宿東口', '地下街直通'],
    notes: 'JR 新宿站東口出站步行 1 分鐘，相機、智慧型手機、美妝家電一站購足。'
  },
  {
    code: 'yodobashi-ikebukuro',
    name: '友都八喜 Multimedia池袋店',
    nameJa: 'ヨドバシカメラ マルチメディア池袋',
    region: '關東',
    prefecture: '東京都',
    address: '東京都豊島区南池袋1-28-1 西武池袋本店',
    lat: 35.7289,
    lng: 139.7118,
    phone: '03-3988-1010',
    url: 'https://www.yodobashi.com/ec/store/0016/index.html',
    tags: ['免稅 (Tax-Free)', '大型電器城', '池袋站東口直結', '西武池袋百貨'],
    notes: 'JR / 東武 / 西武池袋站直結，全館最新進駐旗艦型展示。'
  },
  {
    code: 'yodobashi-ueno',
    name: '友都八喜 Multimedia上野店',
    nameJa: 'ヨドバシカメラ マルチメディア上野',
    region: '關東',
    prefecture: '東京都',
    address: '東京都台東区上野4-10-10',
    lat: 35.7115,
    lng: 139.7744,
    phone: '03-3837-1010',
    url: 'https://www.yodobashi.com/ec/store/0025/index.html',
    tags: ['免稅 (Tax-Free)', '出示折價券', '上野阿美橫町旁', 'JR上野站不忍口'],
    notes: 'JR 上野站不忍口對面、阿美橫町入口旁，分為 1 號館與 2 號館。'
  },
  {
    code: 'yodobashi-kinshicho',
    name: '友都八喜 Multimedia錦糸町店',
    nameJa: 'ヨドバシカメラ マルチメディア錦糸町',
    region: '關東',
    prefecture: '東京都',
    address: '東京都墨田区江東橋3-14-5 テルミナ 1F-3F',
    lat: 35.6963,
    lng: 139.8142,
    phone: '03-3632-1010',
    url: 'https://www.yodobashi.com/ec/store/0023/index.html',
    tags: ['免稅 (Tax-Free)', '大型電器城', '錦糸町站直通', 'TERMINA百貨'],
    notes: 'JR 錦糸町站南口 TERMINA 百貨 1 至 3 樓，晴空塔旁大型電器商城。'
  },
  {
    code: 'yodobashi-kichijoji',
    name: '友都八喜 Multimedia吉祥寺店',
    nameJa: 'ヨドバシカメラ マルチメディア吉祥寺',
    region: '關東',
    prefecture: '東京都',
    address: '東京都武蔵野市吉祥寺本町1-19-1',
    lat: 35.7046,
    lng: 139.5808,
    phone: '0422-29-1010',
    url: 'https://www.yodobashi.com/ec/store/0029/index.html',
    tags: ['免稅 (Tax-Free)', '大型電器城', '吉祥寺站北口', '大型專門店'],
    notes: 'JR 吉祥寺站北口步行 3 分鐘，B1 至 5 樓電器城，6 至 8 樓為 GU、UNIQLO 等商場。'
  },
  {
    code: 'yodobashi-machida',
    name: '友都八喜 Multimedia町田店',
    nameJa: 'ヨドバシカメラ マルチメディア町田',
    region: '關東',
    prefecture: '東京都',
    address: '東京都町田市原町田1-1-11',
    lat: 35.5418,
    lng: 139.4475,
    phone: '042-721-1010',
    url: 'https://www.yodobashi.com/ec/store/0027/index.html',
    tags: ['免稅 (Tax-Free)', '大型電器城', 'JR町田站南口直通'],
    notes: 'JR 町田站南口出站即達，獨立大樓全館電器商城。'
  },
  {
    code: 'yodobashi-hachioji',
    name: '友都八喜 八王子店',
    nameJa: 'ヨドバシカメラ 八王子店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都八王子市明神町3-27-1',
    lat: 35.6582,
    lng: 139.3402,
    phone: '042-643-1010',
    url: 'https://www.yodobashi.com/ec/store/0028/index.html',
    tags: ['免稅 (Tax-Free)', '京王八王子站直結'],
    notes: '京王八王子站大樓直結，西東京大型電器據點。'
  },
  {
    code: 'yodobashi-yokohama',
    name: '友都八喜 Multimedia橫濱旗艦店',
    nameJa: 'ヨドバシカメラ マルチメディア横浜',
    region: '關東',
    prefecture: '神奈川縣',
    address: '神奈川県横浜市西区北幸1-2-7',
    lat: 35.4668,
    lng: 139.6208,
    phone: '045-313-1010',
    url: 'https://www.yodobashi.com/ec/store/0033/index.html',
    tags: ['免稅 (Tax-Free)', '大型電器城', '橫濱站西口直通', '地下街直結', '餐廳街'],
    notes: '橫濱站西口地下街直結，B1 至 7 樓超大型電器旗艦店，8 樓為美食餐廳街。'
  },
  {
    code: 'yodobashi-kawasaki',
    name: '友都八喜 Multimedia川崎LeFront店',
    nameJa: 'ヨドバシカメラ マルチメディア川崎ルフロン',
    region: '關東',
    prefecture: '神奈川縣',
    address: '神奈川県川崎市川崎区日進町1-11 川崎ルフロン B1F-4F',
    lat: 35.5292,
    lng: 139.6994,
    phone: '044-221-1010',
    url: 'https://www.yodobashi.com/ec/store/0034/index.html',
    tags: ['免稅 (Tax-Free)', '大型電器城', '川崎站東口', 'LeFront商場'],
    notes: 'JR 川崎站東口步行 2 分鐘 LeFront 商場 B1 至 4 樓，品項豐富。'
  },
  {
    code: 'yodobashi-kamiooka',
    name: '友都八喜 Multimedia京急上大岡店',
    nameJa: 'ヨドバシカメラ マルチメディア京急上大岡',
    region: '關東',
    prefecture: '神奈川縣',
    address: '神奈川県横浜市港南区上大岡西1-6-1 京急百貨店 6F-9F',
    lat: 35.4085,
    lng: 139.5962,
    phone: '045-845-1010',
    url: 'https://www.yodobashi.com/ec/store/0037/index.html',
    tags: ['免稅 (Tax-Free)', '大型電器城', '京急上大岡站直結', '京急百貨內'],
    notes: '京急線與橫濱市營地下鐵上大岡站直結京急百貨 6 至 9 樓，橫濱南部最大型家電專門百貨。'
  },
  {
    code: 'yodobashi-saitama',
    name: '友都八喜 Multimedia埼玉新都心站前店',
    nameJa: 'ヨドバシカメラ マルチメディアさいたま新都心駅前店',
    region: '關東',
    prefecture: '埼玉縣',
    address: '埼玉県さいたま市大宮区吉敷町4-263-6 コクーン3',
    lat: 35.8953,
    lng: 139.6362,
    phone: '048-645-1010',
    url: 'https://www.yodobashi.com/ec/store/0031/index.html',
    tags: ['免稅 (Tax-Free)', '大型電器城', '埼玉新都心站直通', 'Cocoon City'],
    notes: 'JR 埼玉新都心站東口直通 Cocoon 3 整棟，埼玉縣最大規模友都八喜。'
  },
  {
    code: 'yodobashi-chiba',
    name: '友都八喜 Multimedia千葉店',
    nameJa: 'ヨドバシカメラ マルチメディア千葉',
    region: '關東',
    prefecture: '千葉縣',
    address: '千葉県千葉市中央区富士見2-3-1 塚本大千葉ビル',
    lat: 35.6118,
    lng: 140.1165,
    phone: '043-224-1010',
    url: 'https://www.yodobashi.com/ec/store/0038/index.html',
    tags: ['免稅 (Tax-Free)', '大型電器城', '千葉站東口'],
    notes: 'JR 千葉站東口出站步行 2 分鐘，千葉縣核心電器專門百貨。'
  },

  // --- 近畿關西圈 (大阪 / 京都) ---
  {
    code: 'yodobashi-umeda',
    name: '友都八喜 Multimedia梅田旗艦店 (LINKS UMEDA)',
    nameJa: 'ヨドバシカメラ マルチメディア梅田',
    region: '近畿',
    prefecture: '大阪府',
    address: '大阪府大阪市北区大深町1-1 LINKS UMEDA',
    lat: 34.7038,
    lng: 135.4965,
    phone: '06-4802-1010',
    url: 'https://www.yodobashi.com/ec/store/0081/index.html',
    tags: ['免稅 (Tax-Free)', '大型電器城', '關西最大旗艦店', '大阪站直通', 'LINKS UMEDA', '退稅專屬通道'],
    notes: '全關西規模最大、營收第一的超巨型購物地標！B2 至 8 樓電器城＋LINKS 百貨，與 JR 大阪站、阪急梅田站地下街直接貫通。'
  },
  {
    code: 'yodobashi-kyoto',
    name: '友都八喜 Multimedia京都店 (京都Yodobashi)',
    nameJa: 'ヨドバシカメラ マルチメディア京都',
    region: '近畿',
    prefecture: '京都府',
    address: '京都府京都市下京区烏丸通七条下る東塩小路町590-2',
    lat: 34.9875,
    lng: 135.7592,
    phone: '075-351-1010',
    url: 'https://www.yodobashi.com/ec/store/0083/index.html',
    tags: ['免稅 (Tax-Free)', '大型電器城', 'JR京都站烏丸口直結', '京都旗艦館', '地下街直通'],
    notes: 'JR 京都站烏丸口地下通道直接相連，B1 至 3 樓電器城，高樓層有 UNIQLO、玩具與美食街。'
  },

  // --- 中部 / 東海 (名古屋) ---
  {
    code: 'yodobashi-nagoya',
    name: '友都八喜 Multimedia名古屋松坂屋店',
    nameJa: 'ヨドバシカメラ マルチメディア名古屋松坂屋店',
    region: '中部',
    prefecture: '愛知縣',
    address: '愛知県名古屋市中区栄3-16-1 松坂屋名古屋店 南館 4F-6F',
    lat: 35.1648,
    lng: 136.9085,
    phone: '052-265-1010',
    url: 'https://www.yodobashi.com/ec/store/0085/index.html',
    tags: ['免稅 (Tax-Free)', '大型電器城', '榮商圈', '松坂屋百貨南館'],
    notes: '地鐵名城線矢場町站直通松坂屋南館 4 至 6 樓，榮商圈核心大型電器城。'
  },

  // --- 北海道 / 東北 ---
  {
    code: 'yodobashi-sapporo',
    name: '友都八喜 Multimedia札幌店',
    nameJa: 'ヨドバシカメラ マルチメディア札幌',
    region: '北海道・東北',
    prefecture: '北海道',
    address: '北海道札幌市北区北6条西5-1-22',
    lat: 43.0694,
    lng: 141.3488,
    phone: '011-808-1010',
    url: 'https://www.yodobashi.com/ec/store/0063/index.html',
    tags: ['免稅 (Tax-Free)', '大型電器城', '札幌站北口出站即達', '北海道旗艦館'],
    notes: 'JR 札幌站北口出站步行 1 分鐘，北海道規模最大電器量販，冬季直通地下道便利防雪。'
  },
  {
    code: 'yodobashi-sendai',
    name: '友都八喜 Multimedia仙台店 (Yodobashi仙台)',
    nameJa: 'ヨドバシカメラ マルチメディア仙台',
    region: '北海道・東北',
    prefecture: '宮城縣',
    address: '宮城県仙台市宮城野区榴岡1-3-1 ヨドバシ仙台第1ビル',
    lat: 38.2595,
    lng: 140.8845,
    phone: '022-295-1010',
    url: 'https://www.yodobashi.com/ec/store/0058/index.html',
    tags: ['免稅 (Tax-Free)', '大型電器城', '仙台站東口直結', '東北最大旗艦'],
    notes: 'JR 仙台站東口天橋直接相連，全新第 1 大樓完工，全東北面積最大的電器旗艦店。'
  },
  {
    code: 'yodobashi-koriyama',
    name: '友都八喜 Multimedia郡山店',
    nameJa: 'ヨドバシカメラ マルチメディア郡山',
    region: '北海道・東北',
    prefecture: '福島縣',
    address: '福島県郡山市駅前1-16-7 ATi郡山 B1F-3F',
    lat: 37.3975,
    lng: 140.3878,
    phone: '024-931-1010',
    url: 'https://www.yodobashi.com/ec/store/0053/index.html',
    tags: ['免稅 (Tax-Free)', '出示折價券', '郡山站西口直通', 'ATi郡山商場'],
    notes: 'JR 郡山站西口步行 1 分鐘 ATi 郡山，南東北交通核心店。'
  },
  {
    code: 'yodobashi-utsunomiya',
    name: '友都八喜 Multimedia宇都宮店',
    nameJa: 'ヨドバシカメラ マルチメディア宇都宮',
    region: '關東',
    prefecture: '栃木縣',
    address: '栃木県宇都宮市駅前通り1-4-6 トナリエ宇都宮 B1F-2F',
    lat: 36.5605,
    lng: 139.8972,
    phone: '028-600-1010',
    url: 'https://www.yodobashi.com/ec/store/0052/index.html',
    tags: ['免稅 (Tax-Free)', '宇都宮站西口直通', 'Tonarie宇都宮'],
    notes: 'JR 宇都宮站西口天橋直結商場，北關東旗艦電器店。'
  },
  {
    code: 'yodobashi-niigata',
    name: '友都八喜 Multimedia新潟站前店',
    nameJa: 'ヨドバシカメラ マルチメディア新潟駅前店',
    region: '中部',
    prefecture: '新潟縣',
    address: '新潟県新潟市中央区弁天1-2-6',
    lat: 37.9128,
    lng: 139.0608,
    phone: '025-249-1010',
    url: 'https://www.yodobashi.com/ec/store/0051/index.html',
    tags: ['免稅 (Tax-Free)', '出示折價券', 'JR新潟站萬代口'],
    notes: 'JR 新潟站萬代口出站步行 1 分鐘，北陸甲信越大型電器專賣店。'
  },
  {
    code: 'yodobashi-kofu',
    name: '友都八喜 Multimedia甲府店',
    nameJa: 'ヨドバシカメラ マルチメディア甲府',
    region: '中部',
    prefecture: '山梨縣',
    address: '山梨県甲府市丸の内1-3-3',
    lat: 35.6662,
    lng: 138.5684,
    phone: '055-230-1010',
    url: 'https://www.yodobashi.com/ec/store/0055/index.html',
    tags: ['免稅 (Tax-Free)', '出示折價券', '甲府站南口出站即達'],
    notes: 'JR 甲府站南口出站即達，山梨縣最大型電器 3C 與生活用品城。'
  },

  // --- 九州 ---
  {
    code: 'yodobashi-hakata',
    name: '友都八喜 Multimedia博多旗艦店',
    nameJa: 'ヨドバシカメラ マルチメディア博多',
    region: '九州・沖繩',
    prefecture: '福岡縣',
    address: '福岡県福岡市博多区博多駅中央街6-12',
    lat: 33.5882,
    lng: 130.4225,
    phone: '092-471-1010',
    url: 'https://www.yodobashi.com/ec/store/0088/index.html',
    tags: ['免稅 (Tax-Free)', '大型電器城', '九州最大旗艦店', '博多站筑紫口直達', '退稅專屬通道', '美食街'],
    notes: '全九州最大型電器百貨！JR 博多站筑紫口出站步行 1 分鐘，地下 1 樓至地上 3 樓電器城，4 樓為美食餐廳街與動漫商場。'
  }
];

export const KOJIMA_BIC_SEED = [
  {
    code: 'kojima-naha',
    name: 'Kojima × Bic Camera 那霸店',
    nameJa: 'コジマ×ビックカメラ 那覇店',
    region: '九州・沖繩',
    prefecture: '沖繩縣',
    address: '沖縄県那覇市字安謝664-5',
    lat: 26.2378,
    lng: 127.6965,
    phone: '098-941-3001',
    url: 'https://www.kojima.net/shop/shoplist/naha.html',
    tags: ['免稅 (Tax-Free)', 'Kojima x Bic Camera', '沖繩自駕首選', '大型量販店', '出示折價券'],
    notes: '那霸安謝 58 號國道旁超大型獨立店，停車場極廣，外國旅客自駕採購家電熱點。'
  },
  {
    code: 'kojima-shimura',
    name: 'Kojima × Bic Camera 志村店',
    nameJa: 'コジマ×ビックカメラ 志村店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都板橋区坂下1-35-1',
    lat: 35.7818,
    lng: 139.6892,
    phone: '03-5914-2211',
    url: 'https://www.kojima.net/',
    tags: ['免稅 (Tax-Free)', 'Kojima x Bic Camera', '都營三田線沿線'],
    notes: '都營三田線蓮根站/志村三丁目站旁，社區大型綜合家電生活館。'
  },
  {
    code: 'kojima-edogawa',
    name: 'Kojima × Bic Camera 江戶川店',
    nameJa: 'コジマ×ビックカメラ 江戸川店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都江戸川区中央1-8-15',
    lat: 35.7042,
    lng: 139.8698,
    phone: '03-5662-8111',
    url: 'https://www.kojima.net/',
    tags: ['免稅 (Tax-Free)', 'Kojima x Bic Camera', '家電專門'],
    notes: '東京東區大型獨立家電商場，免稅退稅對應。'
  },
  {
    code: 'kojima-seijo',
    name: 'Kojima × Bic Camera 成城店',
    nameJa: 'コジマ×ビックカメラ 成城店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都世田谷区給田2-1-3',
    lat: 35.6612,
    lng: 139.5885,
    phone: '03-5384-2111',
    url: 'https://www.kojima.net/',
    tags: ['免稅 (Tax-Free)', 'Kojima x Bic Camera', '京王線沿線'],
    notes: '京王線千歲烏山/仙川站周邊，世田谷區大型量販店。'
  },
  {
    code: 'kojima-kohoku',
    name: 'Kojima × Bic Camera 港北東急S.C.店',
    nameJa: 'コジマ×ビックカメラ 港北東急S.C.店',
    region: '關東',
    prefecture: '神奈川縣',
    address: '神奈川県横浜市都筑区茅ケ崎中央5-1 港北東急S.C. B馆 1F-2F',
    lat: 35.5422,
    lng: 139.5732,
    phone: '045-949-5111',
    url: 'https://www.kojima.net/',
    tags: ['免稅 (Tax-Free)', 'Kojima x Bic Camera', '港北New Town', '地下鐵直結'],
    notes: '橫濱市營地下鐵中心南站直通購物中心，高品項家電城。'
  },
  {
    code: 'kojima-kajigaya',
    name: 'Kojima × Bic Camera 梶谷店',
    nameJa: 'コジマ×ビックカメラ 梶ヶ谷店',
    region: '關東',
    prefecture: '神奈川縣',
    address: '神奈川県川崎市高津区梶ケ谷6-2-3',
    lat: 35.5795,
    lng: 139.6012,
    phone: '044-860-2511',
    url: 'https://www.kojima.net/',
    tags: ['免稅 (Tax-Free)', 'Kojima x Bic Camera', '川崎高津區'],
    notes: '東急田園都市線梶谷站生活圈，獨立大樓大型量販。'
  },
  {
    code: 'kojima-urawa',
    name: 'Kojima × Bic Camera 浦和店',
    nameJa: 'コジマ×ビックカメラ 浦和店',
    region: '關東',
    prefecture: '埼玉縣',
    address: '埼玉県さいたま市緑区原山4-34-1',
    lat: 35.8672,
    lng: 139.6782,
    phone: '048-813-1111',
    url: 'https://www.kojima.net/',
    tags: ['免稅 (Tax-Free)', 'Kojima x Bic Camera', '埼玉主要門市'],
    notes: '國道 463 號旁，埼玉南部佔地廣闊之家電生活館。'
  },
  {
    code: 'kojima-makuhari',
    name: 'Kojima × Bic Camera 幕張店',
    nameJa: 'コジマ×ビックカメラ 幕張店',
    region: '關東',
    prefecture: '千葉縣',
    address: '千葉県習志野市芝園1-1-1',
    lat: 35.6568,
    lng: 140.0125,
    phone: '047-453-8111',
    url: 'https://www.kojima.net/',
    tags: ['免稅 (Tax-Free)', 'Kojima x Bic Camera', '海濱幕張', '近幕張展覽館'],
    notes: 'JR 新習志野/海濱幕張周邊，近幕張展覽館 Messe，商場腹地大。'
  },
  {
    code: 'kojima-kashiwa',
    name: 'Kojima × Bic Camera 柏店',
    nameJa: 'コジマ×ビックカメラ 柏店',
    region: '關東',
    prefecture: '千葉縣',
    address: '千葉県柏市十余二249-5',
    lat: 35.8925,
    lng: 139.9572,
    phone: '04-7135-2111',
    url: 'https://www.kojima.net/',
    tags: ['免稅 (Tax-Free)', 'Kojima x Bic Camera', '國道16號旁'],
    notes: '國道 16 號沿線大型量販專門店。'
  },
  {
    code: 'kojima-fukuoka-nishi',
    name: 'Kojima × Bic Camera 福岡西店',
    nameJa: 'コジマ×ビックカメラ 福岡西店',
    region: '九州・沖繩',
    prefecture: '福岡縣',
    address: '福岡県福岡市西区拾六町1-2-30',
    lat: 33.5682,
    lng: 130.3165,
    phone: '092-894-1111',
    url: 'https://www.kojima.net/',
    tags: ['免稅 (Tax-Free)', 'Kojima x Bic Camera', '福岡西區樞紐'],
    notes: '福岡都市高速環狀線旁，福岡西區規模最大電器量販。'
  },
  {
    code: 'kojima-ibaraki',
    name: 'Kojima × Bic Camera 茨木太田店',
    nameJa: 'コジマ×ビックカメラ イオンタウン茨木太田店',
    region: '近畿',
    prefecture: '大阪府',
    address: '大阪府茨木市城の前町2-1 イオンタウン茨木太田 2F',
    lat: 34.8342,
    lng: 135.5685,
    phone: '072-620-8111',
    url: 'https://www.kojima.net/',
    tags: ['免稅 (Tax-Free)', 'Kojima x Bic Camera', '永旺商城內', '北攝生活圈'],
    notes: '大阪北攝地區最新 AEON TOWN 2 樓，免稅對應便利。'
  },
  {
    code: 'kojima-fushimi',
    name: 'Kojima × Bic Camera 伏見店',
    nameJa: 'コジマ×ビックカメラ 伏見店',
    region: '近畿',
    prefecture: '京都府',
    address: '京都府京都市伏見区下鳥羽平塚町131',
    lat: 34.9388,
    lng: 135.7512,
    phone: '075-604-5111',
    url: 'https://www.kojima.net/',
    tags: ['免稅 (Tax-Free)', 'Kojima x Bic Camera', '京都南區樞紐'],
    notes: '國道 1 號京阪國道旁，京都南部超大型綜合電器店。'
  },
  {
    code: 'kojima-sapporo',
    name: 'Kojima × Bic Camera 札幌手稻店',
    nameJa: 'コジマ×ビックカメラ 手稲店',
    region: '北海道・東北',
    prefecture: '北海道',
    address: '北海道札幌市手稲区前田5条13丁目3-1',
    lat: 43.1285,
    lng: 141.2582,
    phone: '011-686-2111',
    url: 'https://www.kojima.net/',
    tags: ['免稅 (Tax-Free)', 'Kojima x Bic Camera', '札幌市區量販'],
    notes: 'JR 手稻站生活圈，北海道大型獨立店。'
  },
  {
    code: 'kojima-sendai',
    name: 'Kojima × Bic Camera 泉中央店',
    nameJa: 'コジマ×ビックカメラ 泉中央店',
    region: '北海道・東北',
    prefecture: '宮城縣',
    address: '宮城県仙台市泉区泉中央3-3-1',
    lat: 38.3242,
    lng: 140.8835,
    phone: '022-772-2111',
    url: 'https://www.kojima.net/',
    tags: ['免稅 (Tax-Free)', 'Kojima x Bic Camera', '仙台地下鐵終點站'],
    notes: '仙台市營地下鐵泉中央站步行 3 分鐘，東北北部生活樞紐。'
  }
];

export const SOFMAP_SEED = [
  {
    code: 'sofmap-akiba-pc',
    name: 'Sofmap AKIBA 電腦・數位旗艦館',
    nameJa: 'ソフマップ AKIBA パソコン・デジタル館',
    region: '關東',
    prefecture: '東京都',
    address: '東京都千代田区外神田3-13-12 IMYビル',
    lat: 35.7005,
    lng: 139.7712,
    phone: '03-3253-1111',
    url: 'https://www.sofmap.com/tenpo/contents/?id=shops&sid=akiba_pc',
    tags: ['免稅 (Tax-Free)', 'Sofmap', '秋葉原電氣街', '自組電腦電競', '二手3C', 'Apple專門'],
    notes: '秋葉原中央通指標門市，PC/Mac 自組電腦、電競周邊與優質二手 3C 免稅旗艦。'
  },
  {
    code: 'sofmap-akiba-anime',
    name: 'Sofmap AKIBA 娛樂動漫館',
    nameJa: 'ソフマップ AKIBA アミューズメント館',
    region: '關東',
    prefecture: '東京都',
    address: '東京都千代田区外神田1-10-8 平岡ビル',
    lat: 35.6985,
    lng: 139.7718,
    phone: '03-3253-3030',
    url: 'https://www.sofmap.com/tenpo/contents/?id=shops&sid=akiba_ams',
    tags: ['免稅 (Tax-Free)', 'Sofmap', '動漫模型', 'TV遊戲電玩', '偶像周邊', '秋葉原站前'],
    notes: 'JR 秋葉原站電氣街口步行 2 分鐘，電視遊戲、模型公仔、Anime DVD 免稅專賣。'
  },
  {
    code: 'sofmap-shinjuku',
    name: 'Sofmap 新宿店',
    nameJa: 'ソフマップ 新宿店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都新宿区西新宿1-5-1 小田急ハルク 2F',
    lat: 35.6923,
    lng: 139.6991,
    phone: '03-3343-1111',
    url: 'https://www.sofmap.com/tenpo/contents/?id=shops&sid=shinjuku',
    tags: ['免稅 (Tax-Free)', 'Sofmap', '新宿西口HALC', '車站直結'],
    notes: '小田急 HALC 百貨 2 樓與 Bic Camera 專門區連通，相機、筆電二手與免稅服務。'
  },
  {
    code: 'sofmap-omiya',
    name: 'Sofmap 大宮ARCHE店',
    nameJa: 'ソフマップ 大宮アルシェ店',
    region: '關東',
    prefecture: '埼玉縣',
    address: '埼玉県さいたま市大宮区桜木町2-1-1 大宮アルシェ 1F',
    lat: 35.9062,
    lng: 139.6228,
    phone: '048-648-1111',
    url: 'https://www.sofmap.com/tenpo/contents/?id=shops&sid=omiya',
    tags: ['免稅 (Tax-Free)', 'Sofmap', '大宮站西口直結', 'ARCHE商場'],
    notes: 'JR 大宮站西口天橋直結 ARCHE 百貨 1 樓，電玩動漫與數位商品齊全。'
  },
  {
    code: 'sofmap-kawasaki',
    name: 'Sofmap 川崎店',
    nameJa: 'ソフマップ 川崎店',
    region: '關東',
    prefecture: '神奈川縣',
    address: '神奈川県川崎市幸区堀川町72-1 ラゾーナ川崎プラザ 4F',
    lat: 35.5328,
    lng: 139.6965,
    phone: '044-520-1111',
    url: 'https://www.sofmap.com/tenpo/contents/?id=shops&sid=kawasaki',
    tags: ['免稅 (Tax-Free)', 'Sofmap', '川崎站直結', 'Lazona商場'],
    notes: 'Lazona 川崎廣場 4 樓，Bic Camera 門市內專門館，主打遊戲電玩與動漫。'
  },
  {
    code: 'sofmap-nagoya',
    name: 'Sofmap 名古屋站西店',
    nameJa: 'ソフマップ 名古屋駅西店',
    region: '中部',
    prefecture: '愛知縣',
    address: '愛知県名古屋市中村区椿町6-9 ビックカメラ名古屋駅西店 B1F',
    lat: 35.1704,
    lng: 136.8804,
    phone: '052-459-1111',
    url: 'https://www.sofmap.com/tenpo/contents/?id=shops&sid=nagoya',
    tags: ['免稅 (Tax-Free)', 'Sofmap', '名古屋站太閤通口', 'BicCamera地下1樓'],
    notes: '名古屋站新幹線口 Bic Camera 地下 1 樓，中部動漫電玩與二手 3C 指標店。'
  },
  {
    code: 'sofmap-namba',
    name: 'Sofmap 難波日本橋店',
    nameJa: 'ソフマップ なんば店',
    region: '近畿',
    prefecture: '大阪府',
    address: '大阪府大阪市浪速区日本橋3-6-18',
    lat: 34.6642,
    lng: 135.5058,
    phone: '06-6634-1111',
    url: 'https://www.sofmap.com/tenpo/contents/?id=shops&sid=nanba',
    tags: ['免稅 (Tax-Free)', 'Sofmap', '大阪日本橋電氣街', '關西動漫電玩聖地'],
    notes: '大阪日本橋 Ota Road (オタロード) 動漫電玩街正中心，關西 Sofmap 旗艦總店。'
  },
  {
    code: 'sofmap-kobe',
    name: 'Sofmap 神戶Harborland店',
    nameJa: 'ソフマップ 神戸ハーバーランド店',
    region: '近畿',
    prefecture: '兵庫縣',
    address: '兵庫県神戸市中央区東川崎町1-7-2 umie NORTH MALL 6F',
    lat: 34.6798,
    lng: 135.1812,
    phone: '078-360-1111',
    url: 'https://www.sofmap.com/tenpo/contents/?id=shops&sid=kobe',
    tags: ['免稅 (Tax-Free)', 'Sofmap', '神戶港umie商場', 'JR神戶站直通'],
    notes: '神戶 Harborland umie 北館 6 樓，神戶地區綜合 3C 電玩旗艦。'
  },
  {
    code: 'sofmap-sendai',
    name: 'Sofmap 仙台站前店',
    nameJa: 'ソフマップ 仙台駅西口店',
    region: '北海道・東北',
    prefecture: '宮城縣',
    address: '宮城県仙台市青葉区中央4-1-1 4F',
    lat: 38.2588,
    lng: 140.8805,
    phone: '022-726-1111',
    url: 'https://www.sofmap.com/tenpo/contents/?id=shops&sid=sendai',
    tags: ['免稅 (Tax-Free)', 'Sofmap', '仙台站西口直通', '東北電玩動漫'],
    notes: 'Bic Camera 仙台店 4 樓，東北最大動漫模型與遊戲專門館。'
  },
  {
    code: 'sofmap-tenjin',
    name: 'Sofmap 天神1號館店',
    nameJa: 'ソフマップ 天神1号館店',
    region: '九州・沖繩',
    prefecture: '福岡縣',
    address: '福岡県福岡市中央区今泉1-25-1 ビックカメラ天神1号館 2F',
    lat: 33.5878,
    lng: 130.3995,
    phone: '092-732-1111',
    url: 'https://www.sofmap.com/tenpo/contents/?id=shops&sid=tenjin',
    tags: ['免稅 (Tax-Free)', 'Sofmap', '福岡天神商圈', '西鐵天神站直達'],
    notes: 'Bic Camera 天神 1 號館 2 樓，九州動漫電玩二手 3C 旗艦。'
  }
];

export function buildElectronicsStores(seedList, brandName, stationsList = []) {
  return seedList.map(item => {
    let nearestStation = item.name.includes('站') || item.name.includes('空港') ? item.name : `${item.prefecture}主要車站`;
    let stationLine = 'JR / 地鐵 / 私鐵';
    let walkMin = 2;

    const matched = stationsList.find(st => 
      item.address.includes(st.name.replace(/站$/, '')) || 
      item.name.includes(st.name.replace(/站$/, ''))
    );

    if (matched) {
      nearestStation = matched.name;
      stationLine = matched.lines?.[0] || 'JR / 地鐵';
    }

    let defaultImg = 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=800&q=80';
    if (brandName.includes('Yodobashi') || brandName.includes('友都八喜')) {
      defaultImg = 'https://images.unsplash.com/photo-1526738549149-8e07eca6c147?auto=format&fit=crop&w=800&q=80';
    } else if (brandName.includes('Sofmap')) {
      defaultImg = 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=80';
    }

    return {
      id: item.code,
      category: '購物藥妝',
      brand: brandName,
      name: item.name,
      nameJa: item.nameJa,
      region: item.region,
      prefecture: item.prefecture,
      nearestStation,
      stationLine,
      stationAccess: `鄰近 ${nearestStation} 步行約 ${walkMin} 分鐘`,
      walkMinutes: walkMin,
      address: item.address,
      coordinates: `${item.lat}, ${item.lng}`,
      lat: item.lat,
      lng: item.lng,
      phone: item.phone,
      bookingUrl: item.url,
      googleMapUrl: `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(item.nameJa)}`,
      imageUrl: defaultImg,
      images: [defaultImg],
      tags: item.tags.join(', '),
      notes: item.notes
    };
  });
}

export function getAllElectronicsSpots(stationsList = []) {
  const bicSpots = buildElectronicsStores(BIC_CAMERA_SEED, 'Bic Camera', stationsList);
  const yodobashiSpots = buildElectronicsStores(YODOBASHI_SEED, '友都八喜 (Yodobashi)', stationsList);
  const kojimaSpots = buildElectronicsStores(KOJIMA_BIC_SEED, 'Kojima × Bic Camera', stationsList);
  const sofmapSpots = buildElectronicsStores(SOFMAP_SEED, 'Sofmap (ソフマップ)', stationsList);

  const combined = [...bicSpots, ...yodobashiSpots, ...kojimaSpots, ...sofmapSpots];
  const { uniqueSpots } = deduplicateSpots(combined);
  const validation = validateSpotsBatch(uniqueSpots);
  console.log(`[Electronics] 成功建立 Bic Camera (${bicSpots.length}) + Yodobashi (${yodobashiSpots.length}) + Kojima×Bic (${kojimaSpots.length}) + Sofmap (${sofmapSpots.length})，總計 ${uniqueSpots.length} 間，通過驗證 ${validation.validCount} 間`);
  return uniqueSpots;
}

