/**
 * =========================================================================
 * 松本清 (Matsumoto Kiyoshi) 門市爬蟲與資料模組
 * =========================================================================
 * 收錄全日本台灣旅客最常前往的主要城市、樞紐商圈與國際機場免稅門市。
 * 包含：東京首都圈、關西(大阪/京都/神戶)、北海道(札幌/小樽/函館)、
 * 沖繩(那霸/美國村/來客夢)、九州(福岡/熊本/鹿兒島/長崎)、
 * 中部東海(名古屋/金澤/輕井澤)、中國四國(廣島/岡山/四國)與東北。
 */

import { findNearestStation } from '../core/geo.js';
import { validateSpotsBatch } from '../core/validator.js';
import { deduplicateSpots } from '../core/dedupe.js';

export const MATSUKIYO_STORES_SEED = [
  // ==========================================
  // 1. 東京首都圈 (Tokyo & Kanto)
  // ==========================================
  {
    code: 'matsukiyo-shinjuku-east',
    name: '松本清 新宿東口店',
    nameJa: 'マツモトキヨシ 新宿東口店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都新宿区新宿3-22-6',
    lat: 35.6924,
    lng: 139.7022,
    phone: '03-5360-4231',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '新宿東口商圈', '深夜營業', '退稅專屬通道'],
    notes: '緊鄰 JR 新宿站東口，地下 1 樓至地上 3 樓藥品、美妝、保健品一應俱全。'
  },
  {
    code: 'matsukiyo-shinjuku-west',
    name: '松本清 新宿西口店',
    nameJa: 'マツモトキヨシ 新宿西口駅前店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都新宿区西新宿1-5-1',
    lat: 35.6918,
    lng: 139.6995,
    phone: '03-3343-2228',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '新宿西口直通', '小田急百貨旁'],
    notes: '新宿站西口地下街出口即達，轉乘小田急、京王線前免稅採買首選。'
  },
  {
    code: 'matsukiyo-shinjuku-3chome',
    name: '松本清 新宿三丁目店',
    nameJa: 'マツモトキヨシ 新宿三丁目店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都新宿区新宿3-17-3',
    lat: 35.6908,
    lng: 139.7042,
    phone: '03-5367-6601',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '伊勢丹百貨旁', '新宿三丁目站直達'],
    notes: '鄰近伊勢丹百貨與紀伊國屋書店，多國語言標籤與充足熱門美妝庫存。'
  },
  {
    code: 'matsukiyo-kabukicho',
    name: '松本清 歌舞伎町店',
    nameJa: 'マツモトキヨシ 歌舞伎町店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都新宿区歌舞伎町1-14-3',
    lat: 35.6948,
    lng: 139.7018,
    phone: '03-5272-1080',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '歌舞伎町入口', '24小時營業', '深夜購物'],
    notes: '哥吉拉大道周邊，24小時不打烊，夜間退稅與急需常備藥品超便利。'
  },
  {
    code: 'matsukiyo-shibuya-part1',
    name: '松本清 澀谷 Part 1 店',
    nameJa: 'マツモトキヨシ 渋谷Part1店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都渋谷区宇田川町22-3',
    lat: 35.6601,
    lng: 139.6998,
    phone: '03-3463-8728',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '澀谷十字路口旁', '熱門美妝保養'],
    notes: '澀谷八公口十字路口步行 2 分鐘，外國觀光客超人氣採購點。'
  },
  {
    code: 'matsukiyo-shibuya-part2',
    name: '松本清 澀谷 Part 2 店',
    nameJa: 'マツモトキヨシ 渋谷Part2店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都渋谷区宇田川町23-4',
    lat: 35.6606,
    lng: 139.6994,
    phone: '03-3463-8730',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '澀谷井之頭通', '專櫃彩妝齊全'],
    notes: '緊鄰 Part 1 店，兩層樓美妝保養與美髮用品極為齊全。'
  },
  {
    code: 'matsukiyo-shibuya-dogenzaka',
    name: '松本清 澀谷道玄坂店',
    nameJa: 'マツモトキヨシ 渋谷道玄坂店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都渋谷区道玄坂2-29-14',
    lat: 35.6592,
    lng: 139.6975,
    phone: '03-3461-1250',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', 'SHIBUYA 109旁', '道玄坂'],
    notes: 'SHIBUYA 109 旁，道玄坂潮流購物街必經免稅店。'
  },
  {
    code: 'matsukiyo-harajuku-takeshita',
    name: '松本清 原宿竹下通店',
    nameJa: 'マツモトキヨシ 原宿竹下通り店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都渋谷区神宮前1-8-5',
    lat: 35.6712,
    lng: 139.7045,
    phone: '03-3478-4330',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '原宿竹下通', '潮流美妝推薦'],
    notes: '原宿竹下通核心商圈，年輕流行彩妝與保養品牌最齊全。'
  },
  {
    code: 'matsukiyo-omotesando',
    name: '松本清 表參道原宿店',
    nameJa: 'マツモトキヨシ 表参道原宿店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都渋谷区神宮前4-30-3',
    lat: 35.6685,
    lng: 139.7065,
    phone: '03-5775-6805',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '表參道神宮前', '高階保養彩妝'],
    notes: '神宮前路口，東急PLAZA表參道原宿對面，高質感旗艦店。'
  },
  {
    code: 'matsukiyo-ikebukuro-part2',
    name: '松本清 池袋 Part 2 店',
    nameJa: 'マツモトキヨシ 池袋Part2店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都豊島区東池袋1-22-8',
    lat: 35.7305,
    lng: 139.7152,
    phone: '03-5951-3181',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '太陽城通', '營業至深夜'],
    notes: '池袋東口太陽城 60 通道上，營業至深夜 23:00。'
  },
  {
    code: 'matsukiyo-ikebukuro-east',
    name: '松本清 池袋東口站前店',
    nameJa: 'マツモトキヨシ 池袋東口店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都豊島区東池袋1-3-5',
    lat: 35.7301,
    lng: 139.7125,
    phone: '03-3982-8280',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '池袋東口正對面', '出站即達'],
    notes: 'JR 池袋站東口出站直達，交通超便利，退稅服務快速。'
  },
  {
    code: 'matsukiyo-ikebukuro-west',
    name: '松本清 池袋西口店',
    nameJa: 'マツモトキヨシ 池袋西口駅前店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都豊島区西池袋1-20-1',
    lat: 35.7312,
    lng: 139.7092,
    phone: '03-3988-5188',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '池袋西口公園旁', 'Tobu百貨周邊'],
    notes: '池袋站西口出站 1 分鐘，東武百貨與西口公園商圈核心。'
  },
  {
    code: 'matsukiyo-ginza-5chome',
    name: '松本清 銀座5丁目店',
    nameJa: 'マツモトキヨシ 銀座5丁目店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都中央区銀座5-5-1',
    lat: 35.6705,
    lng: 139.7635,
    phone: '03-3289-0260',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '銀座中央通', '高端專櫃品牌'],
    notes: '座落於銀座晴海通與中央通交會處，專櫃級美妝與專屬退稅通道。'
  },
  {
    code: 'matsukiyo-ginza-namiki',
    name: '松本清 銀座並木通店',
    nameJa: 'マツモトキヨシ 銀座並木通り店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都中央区銀座6-8-7',
    lat: 35.6698,
    lng: 139.7622,
    phone: '03-3571-0810',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '銀座並木通精品街', '頂級保養'],
    notes: '鄰近 GINZA SIX，各類頂級日本藥妝及健康食品齊備。'
  },
  {
    code: 'matsukiyo-yurakucho-itocia',
    name: '松本清 有樂町 ITOCiA 店',
    nameJa: 'マツモトキヨシ 有楽町イトシア店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都千代田区有楽町2-7-1 イトシア B1F',
    lat: 35.6748,
    lng: 139.7645,
    phone: '03-5224-6010',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '有樂町站直結', '銀座入口'],
    notes: 'JR 有樂町站中央口直結 ITOCiA 地下 1 樓，前往銀座必經。'
  },
  {
    code: 'matsukiyo-ueno-ameyoko',
    name: '松本清 上野阿美橫丁店',
    nameJa: 'マツモトキヨシ 上野アメ横店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都台東区上野4-7-17',
    lat: 35.7108,
    lng: 139.7745,
    phone: '03-3836-9730',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '阿美橫丁入口', '折扣力度大', '中文對應'],
    notes: '上野站不忍口正對面，阿美橫町熱門伴手禮與常備藥品免稅專賣。'
  },
  {
    code: 'matsukiyo-ueno-hirokouji',
    name: '松本清 上野廣小路店',
    nameJa: 'マツモトキヨシ 上野広小路店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都台東区上野2-1-10',
    lat: 35.7078,
    lng: 139.7725,
    phone: '03-5818-7010',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '上野廣小路站直結', '松坂屋旁'],
    notes: '銀座線廣小路站與大江戶線上野御徒町站旁，老牌商業街藥妝指標。'
  },
  {
    code: 'matsukiyo-asakusa-kaminarimon',
    name: '松本清 淺草雷門前店',
    nameJa: 'マツモトキヨシ 浅草雷門前店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都台東区浅草1-1-16',
    lat: 35.7115,
    lng: 139.7968,
    phone: '03-5806-0310',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '淺草雷門正對面', '觀光客必訪'],
    notes: '雷門斜對角，觀光客參拜雷門淺草寺後必經的免稅補貨大站。'
  },
  {
    code: 'matsukiyo-asakusa-nitenmon',
    name: '松本清 淺草二天門前店',
    nameJa: 'マツモトキヨシ 浅草二天門前店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都台東区浅草2-34-3',
    lat: 35.7148,
    lng: 139.7979,
    phone: '03-3847-1951',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '淺草寺周邊', '傳統伴手禮'],
    notes: '淺草寺二天門前，觀光客參拜後採購常備藥品熱門門市。'
  },
  {
    code: 'matsukiyo-akihabara-ekimae',
    name: '松本清 秋葉原站前店',
    nameJa: 'マツモトキヨシ アキバ店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都千代田区外神田1-13-1',
    lat: 35.6985,
    lng: 139.7712,
    phone: '03-5297-8811',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '秋葉原電氣街口旁', '車站步行1分內'],
    notes: 'JR 秋葉原站電氣街口出站即達，周邊動漫與 3C 商場林立。'
  },
  {
    code: 'matsukiyo-akihabara-suehirocho',
    name: '松本清 末廣町站前店',
    nameJa: 'マツモトキヨシ 末広町駅前店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都千代田区外神田4-7-5',
    lat: 35.7025,
    lng: 139.7715,
    phone: '03-5298-5010',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '秋葉原中央通北側', '末廣町站直達'],
    notes: '秋葉原中央通北端，神田明神與女僕咖啡街中心地帶。'
  },
  {
    code: 'matsukiyo-tokyo-yaesu',
    name: '松本清 東京站八重洲地下街店',
    nameJa: 'マツモトキヨシ 八重洲地下街店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都中央区八重洲2-1 八重洲地下街中1号',
    lat: 35.6802,
    lng: 139.7695,
    phone: '03-3275-2260',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '東京站八重洲地下街', '搭乘新幹線首選'],
    notes: '東京車站 Yaesu Underground 直通，搭新幹線出發前必買醫藥美妝。'
  },
  {
    code: 'matsukiyo-shinbashi-ginzaguchi',
    name: '松本清 新橋站銀座口店',
    nameJa: 'マツモトキヨシ 新橋駅銀座口店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都港区新橋1-12-9',
    lat: 35.6668,
    lng: 139.7592,
    phone: '03-3571-0810',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '新橋站出口即達', '銀座南端入口'],
    notes: 'JR 新橋站銀座口步行 1 分鐘，直通銀座商圈與汐留。'
  },
  {
    code: 'matsukiyo-shinagawa-konan',
    name: '松本清 品川站港南口店',
    nameJa: 'マツモトキヨシ 品川インターシティ店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都港区港南2-15-2 品川インターシティB1F',
    lat: 35.6268,
    lng: 139.7408,
    phone: '03-5715-1811',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '品川站空橋直通', '羽田/新幹線樞紐'],
    notes: '品川站港南口空橋直通，往返羽田機場或新幹線旅客補貨熱門門市。'
  },
  {
    code: 'matsukiyo-roppongi',
    name: '松本清 六本木店',
    nameJa: 'マツモトキヨシ 六本木店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都港区六本木4-11-11',
    lat: 35.6635,
    lng: 139.7328,
    phone: '03-3478-5771',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '六本木交差點', '深夜營業'],
    notes: '六本木交差點步行 1 分鐘，支援多國語言退稅與醫藥諮詢。'
  },
  {
    code: 'matsukiyo-skytree',
    name: '松本清 東京晴空塔站前店',
    nameJa: 'マツモトキヨシ とうきょうスカイツリー駅前店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都墨田区押上1-1-2',
    lat: 35.7102,
    lng: 139.8118,
    phone: '03-5619-7510',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '晴空塔商圈', '觀光伴手禮'],
    notes: '晴空塔站旁，登塔觀光與墨田水族館遊客免稅購物熱門門市。'
  },
  {
    code: 'matsukiyo-odaiba-aquacity',
    name: '松本清 台場 Aqua City 店',
    nameJa: 'マツモトキヨシ アクアシティお台場店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都港区台場1-7-1 アクアシティお台場 4F',
    lat: 35.6278,
    lng: 139.7712,
    phone: '03-3599-5110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '台場海濱公園', '商場免稅專區'],
    notes: '臨海線台場站直通 Aqua City 4 樓，自由女神像與彩虹大橋觀景勝地。'
  },
  {
    code: 'matsukiyo-haneda-garden',
    name: '松本清 羽田機場花園店',
    nameJa: 'マツモトキヨシ 羽田エアポートガーデン店',
    region: '關東',
    prefecture: '東京都',
    address: '東京都大田区羽田空港2-7-1 羽田エアポートガーデン 2F',
    lat: 35.5458,
    lng: 139.7695,
    phone: '03-5579-7110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '羽田機場第3航廈直通', '出境前最後採購'],
    notes: '直通羽田機場第 3 航廈國際線，登機返台前最後免稅採買據點。'
  },
  {
    code: 'matsukiyo-yokohama-west',
    name: '松本清 橫濱站西口店',
    nameJa: 'マツモトキヨシ 横浜西口店',
    region: '關東',
    prefecture: '神奈川縣',
    address: '神奈川県横浜市西区南幸1-5-1',
    lat: 35.4658,
    lng: 139.6205,
    phone: '045-317-5711',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '橫濱站西口相鐵口', '人氣美妝'],
    notes: '橫濱站西口高島屋與相鐵口旁，神奈川縣客流量最大免稅門市。'
  },
  {
    code: 'matsukiyo-yokohama-chinatown',
    name: '松本清 橫濱中華街善鄰門店',
    nameJa: 'マツモトキヨシ 横浜中華街店',
    region: '關東',
    prefecture: '神奈川縣',
    address: '神奈川県横浜市中区山下町144',
    lat: 35.4435,
    lng: 139.6452,
    phone: '045-662-8110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '橫濱中華街善鄰門旁', '觀光客專區'],
    notes: '元町・中華街觀光區核心，美食巡禮後購買保健醫藥之熱案。'
  },
  {
    code: 'matsukiyo-minatomirai',
    name: '松本清 橫濱港未來Mark Is店',
    nameJa: 'マツモトキヨシ MARK IS みなとみらい店',
    region: '關東',
    prefecture: '神奈川縣',
    address: '神奈川県横浜市西区みなとみらい3-5-1 MARK IS B4F',
    lat: 35.4578,
    lng: 139.6322,
    phone: '045-683-3310',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '港未來站直結', '橫濱美術館旁'],
    notes: '港未來站直結 Mark Is 商場地下，橫濱親子與夜景觀光旅客首選。'
  },
  {
    code: 'matsukiyo-kawasaki-ekimae',
    name: '松本清 川崎站前店',
    nameJa: 'マツモトキヨシ 川崎駅前店',
    region: '關東',
    prefecture: '神奈川縣',
    address: '神奈川県川崎市川崎区駅前本町5-1',
    lat: 35.5312,
    lng: 139.7005,
    phone: '044-245-1210',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '川崎站東口', '地下街Azalea直通'],
    notes: 'JR 川崎站東口與京急川崎站之間，羽田機場進入東京首站。'
  },
  {
    code: 'matsukiyo-kamakura-komachi',
    name: '松本清 鎌倉小町通店',
    nameJa: 'マツモトキヨシ 鎌倉小町通り店',
    region: '關東',
    prefecture: '神奈川縣',
    address: '神奈川県鎌倉市小町1-6-15',
    lat: 35.3198,
    lng: 139.5512,
    phone: '0467-61-3810',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '鎌倉小町通', '鶴岡八幡宮參道'],
    notes: '鎌倉站東口出站進入小町通即達，古都散策免稅補給站。'
  },
  {
    code: 'matsukiyo-makuhari',
    name: '松本清 幕張新都心AEON店',
    nameJa: 'マツモトキヨシ イオンモール幕張新都心店',
    region: '關東',
    prefecture: '千葉縣',
    address: '千葉県千葉市美浜区豊砂1-1 グランドモール 1F',
    lat: 35.6542,
    lng: 140.0195,
    phone: '043-350-0210',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '永旺夢樂城幕張', '旗艦巨型商場'],
    notes: 'JR 幕張豐砂站前，千葉旗艦巨型購物中心內免稅藥妝門市。'
  },

  // ==========================================
  // 2. 關西圈 (大阪 / 神戶 / 關空)
  // ==========================================
  {
    code: 'matsukiyo-shinsaibashi-chuo',
    name: '松本清 心齋橋中央店',
    nameJa: 'マツモトキヨシ 心斎橋中央店',
    region: '近畿',
    prefecture: '大阪府',
    address: '大阪府大阪市中央区心斎橋筋2-1-21',
    lat: 34.6712,
    lng: 135.5008,
    phone: '06-6213-7761',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '心齋橋商店街核心', '中文店員常駐'],
    notes: '大阪最熱門的心齋橋筋商店街中央，台灣旅客掃貨首選據點。'
  },
  {
    code: 'matsukiyo-shinsaibashi-south',
    name: '松本清 心齋橋南店',
    nameJa: 'マツモトキヨシ 心斎橋南店',
    region: '近畿',
    prefecture: '大阪府',
    address: '大阪府大阪市中央区心斎橋筋2-5-5',
    lat: 34.6698,
    lng: 135.5011,
    phone: '06-6214-3011',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '近道頓堀橋', '美妝旗艦'],
    notes: '心齋橋筋南端，步行 1 分鐘即可到道頓堀戎橋，客流極旺。'
  },
  {
    code: 'matsukiyo-shinsaibashi-north',
    name: '松本清 心齋橋北店',
    nameJa: 'マツモトキヨシ 心斎橋筋北店',
    region: '近畿',
    prefecture: '大阪府',
    address: '大阪府大阪市中央区南船場3-11-2',
    lat: 34.6752,
    lng: 135.5005,
    phone: '06-4704-5810',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '南船場精品商圈', '人少逛街舒適'],
    notes: '心齋橋筋往本町方向，品項豐富齊全，結帳排隊較為輕鬆。'
  },
  {
    code: 'matsukiyo-osaka-ebisubashi',
    name: '松本清 難波戎橋店',
    nameJa: 'マツモトキヨシ 戎橋店',
    region: '近畿',
    prefecture: '大阪府',
    address: '大阪府大阪市中央区難波1-5-16',
    lat: 34.6678,
    lng: 135.5015,
    phone: '06-6211-1378',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '道頓堀跑跑人橋旁', '難波站步行3分'],
    notes: '緊鄰道頓堀戎橋與固力果招牌，位置極度顯眼方便。'
  },
  {
    code: 'matsukiyo-namba-sennichimae',
    name: '松本清 難波千日前店',
    nameJa: 'マツモトキヨシ なんば千日前店',
    region: '近畿',
    prefecture: '大阪府',
    address: '大阪府大阪市中央区難波千日前13-10',
    lat: 34.6661,
    lng: 135.5028,
    phone: '06-6644-8810',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '千日前商店街', '難波花月旁'],
    notes: '千日前商店街核心，吉本難波花月劇場旁，美妝藥品一網打盡。'
  },
  {
    code: 'matsukiyo-nankai-namba',
    name: '松本清 南海難波站店',
    nameJa: 'マツモトキヨシ 南海難波駅店',
    region: '近畿',
    prefecture: '大阪府',
    address: '大阪府大阪市中央区難波5-1-60 南海難波駅2F中央改札口',
    lat: 34.6632,
    lng: 135.5021,
    phone: '06-6630-8010',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', 'Rapi:t機場特急改札旁', '關空直通樞紐'],
    notes: '搭乘南海 Rapi:t 前往關西機場改札口旁，出發前補齊免稅戰利品。'
  },
  {
    code: 'matsukiyo-dotonbori-1chome',
    name: '松本清 道頓堀一丁目店',
    nameJa: 'マツモトキヨシ 道頓堀1丁目店',
    region: '近畿',
    prefecture: '大阪府',
    address: '大阪府大阪市中央区道頓堀1-4-25',
    lat: 34.6688,
    lng: 135.5038,
    phone: '06-6214-7710',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '道頓堀河畔', '深夜營業至凌晨'],
    notes: '道頓堀一丁目運河旁，蟹道樂對岸，深夜逛街採購勝地。'
  },
  {
    code: 'matsukiyo-kuromon',
    name: '松本清 黑門市場店',
    nameJa: 'マツモトキヨシ 黒門市場店',
    region: '近畿',
    prefecture: '大阪府',
    address: '大阪府大阪市中央区日本橋1-22-25',
    lat: 34.6655,
    lng: 135.5068,
    phone: '06-6632-1110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '黑門市場入口', '生鮮美食巡禮'],
    notes: '大阪廚房黑門市場拱廊內，品嚐神戶牛海鮮後直接免稅採買。'
  },
  {
    code: 'matsukiyo-umeda-hankyu-sanbangai',
    name: '松本清 梅田阪急三番街店',
    nameJa: 'マツモトキヨシ 阪急三番街店',
    region: '近畿',
    prefecture: '大阪府',
    address: '大阪府大阪市北区芝田1-1-3 阪急三番街南館 B1F',
    lat: 34.7045,
    lng: 135.4988,
    phone: '06-6372-5110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '阪急梅田站直結', '地下街商圈'],
    notes: '阪急大阪梅田站南館 B1F，交通要道，退稅流程流暢迅速。'
  },
  {
    code: 'matsukiyo-whity-umeda',
    name: '松本清 Whity梅田地下街店',
    nameJa: 'マツモトキヨシ ホワイティうめだ店',
    region: '近畿',
    prefecture: '大阪府',
    address: '大阪府大阪市北区角田町 梅田地下街2-5',
    lat: 34.7028,
    lng: 135.4998,
    phone: '06-6312-3210',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', 'Whity梅田泉之廣場旁', '避雨地下街'],
    notes: '全日本最繁華地下街 Whity 梅田內，避暑避雨採購最佳地點。'
  },
  {
    code: 'matsukiyo-umeda-shibata',
    name: '松本清 梅田芝田店',
    nameJa: 'マツモトキヨシ 梅田芝田店',
    region: '近畿',
    prefecture: '大阪府',
    address: '大阪府大阪市北区芝田2-1-3',
    lat: 34.7055,
    lng: 135.4975,
    phone: '06-6376-1181',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', 'Yodobashi梅田對面', '芝田商圈'],
    notes: '友都八喜梅田店北側對面，電器買完直接到松本清補齊藥妝。'
  },
  {
    code: 'matsukiyo-tennoji-abeno',
    name: '松本清 天王寺阿倍野店',
    nameJa: 'マツモトキヨシ あべのキューズモール店',
    region: '近畿',
    prefecture: '大阪府',
    address: '大阪府大阪市阿倍野区阿倍野筋1-6-1 あべのキューズモール B1F',
    lat: 34.6468,
    lng: 135.5125,
    phone: '06-6649-0110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '阿倍野HARUKAS旁', 'Q\'s Mall商場'],
    notes: '大阪最高展望台阿倍野 HARUKAS 旁，Q\'s Mall B1F 寬敞免稅店。'
  },
  {
    code: 'matsukiyo-tennoji-mio',
    name: '松本清 天王寺Mio店',
    nameJa: 'マツモトキヨシ 天王寺ミオ店',
    region: '近畿',
    prefecture: '大阪府',
    address: '大阪府大阪市天王寺区悲田院町10-39 天王寺ミオ本館 2F',
    lat: 34.6478,
    lng: 135.5142,
    phone: '06-6770-1110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', 'JR天王寺站直結', '關空HARUKA停靠站'],
    notes: 'JR 天王寺站直結 Mio 百貨內，關空特急 HARUKA 與大和路快速要衝。'
  },
  {
    code: 'matsukiyo-shin-osaka-ekimarche',
    name: '松本清 Eki Marché新大阪站店',
    nameJa: 'マツモトキヨシ エキマルシェ新大阪店',
    region: '近畿',
    prefecture: '大阪府',
    address: '大阪府大阪市淀川区西中島5-16-1 エキマルシェ新大阪 3F改札内',
    lat: 34.7335,
    lng: 135.5005,
    phone: '06-6309-8010',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '新大阪站改札內', '山陽/東海道新幹線'],
    notes: 'JR 新大阪站在來線與新幹線改札口商場內，轉搭新幹線免稅採買。'
  },
  {
    code: 'matsukiyo-universal-citywalk',
    name: '松本清 日本環球影城走廊店',
    nameJa: 'マツモトキヨシ ユニバーサル・シティウォーク大阪店',
    region: '近畿',
    prefecture: '大阪府',
    address: '大阪府大阪市此花区島屋6-2-61 シティウォーク 3F',
    lat: 34.6672,
    lng: 135.4385,
    phone: '06-4804-1180',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', 'USJ環球影城門前', '休足時間/防曬'],
    notes: 'USJ 環球影城出口商業街，提供休足時間、防曬乳與急需護理藥品。'
  },
  {
    code: 'matsukiyo-kix-t1',
    name: '松本清 關西國際機場店',
    nameJa: 'マツモトキヨシ 関西空港エアロプラザ店',
    region: '近畿',
    prefecture: '大阪府',
    address: '大阪府泉佐野市泉州空港北1番地 エアロプラザ 2F',
    lat: 34.4362,
    lng: 135.2445,
    phone: '072-456-6510',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '關西國際機場Aeroplaza', '搭機前採購'],
    notes: '關西國際機場第 1 航廈與車站連通 Aeroplaza 2F，出境旅客最後補給站。'
  },
  {
    code: 'matsukiyo-kobe-sannomiya-chuo',
    name: '松本清 神戶三宮中央通店',
    nameJa: 'マツモトキヨシ 神戸三宮中央通り店',
    region: '近畿',
    prefecture: '兵庫縣',
    address: '兵庫県神戸市中央区三宮町1-6-18',
    lat: 34.6922,
    lng: 135.1925,
    phone: '078-335-1811',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '三宮Center街', '神戶最熱鬧商圈'],
    notes: '神戶三宮中心街拱廊內，神戶市區客流量最大免稅門市。'
  },
  {
    code: 'matsukiyo-kobe-santica',
    name: '松本清 神戶三宮地下街Santica店',
    nameJa: 'マツモトキヨシ さんちか店',
    region: '近畿',
    prefecture: '兵庫縣',
    address: '兵庫県神戸市中央区三宮町1-10-1 さんちか 6番街',
    lat: 34.6935,
    lng: 135.1948,
    phone: '078-393-2110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', 'Santica地下街直結', 'JR/阪神/阪急三宮直達'],
    notes: '神戶三宮 Santica 地下街 6 號街，轉乘阪神電車與神戶地鐵無縫免稅購物。'
  },
  {
    code: 'matsukiyo-kobe-motomachi',
    name: '松本清 神戶元町商店街店',
    nameJa: 'マツモトキヨシ 神戸元町店',
    region: '近畿',
    prefecture: '兵庫縣',
    address: '兵庫県神戸市中央区元町通1-8-2',
    lat: 34.6895,
    lng: 135.1885,
    phone: '078-333-8110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '元町商店街', '南京町中華街旁'],
    notes: 'JR 元町站東口南側，南京町中華街入口旁，神戶散策必逛。'
  },
  {
    code: 'matsukiyo-himeji-ekimae',
    name: '松本清 姬路站前Miyukidori店',
    nameJa: 'マツモトキヨシ 姫路みゆき通り店',
    region: '近畿',
    prefecture: '兵庫縣',
    address: '兵庫県姫路市駅前町254',
    lat: 34.8312,
    lng: 134.6918,
    phone: '079-287-3110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '姬路城參道', 'みゆき通り商店街'],
    notes: 'JR 姬路站前往世界遺產姬路城必經之 Miyuki 拱廊商店街內。'
  },

  // ==========================================
  // 3. 京都 (Kyoto)
  // ==========================================
  {
    code: 'matsukiyo-kyoto-shijo-kawaramachi',
    name: '松本清 京都四條河原町店',
    nameJa: 'マツモトキヨシ 四条河原町店',
    region: '近畿',
    prefecture: '京都府',
    address: '京都府京都市下京区四条通小橋西入真町88',
    lat: 35.0038,
    lng: 135.7705,
    phone: '075-257-2270',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '阪急河原町站出口', '祇園商圈入口'],
    notes: '阪急京都河原町站出口直達，前往祇園與鴨川必經熱門旗艦店。'
  },
  {
    code: 'matsukiyo-kyoto-shinkyogoku',
    name: '松本清 京都新京極店',
    nameJa: 'マツモトキヨシ 京都新京極店',
    region: '近畿',
    prefecture: '京都府',
    address: '京都府京都市中京区東側町503-17',
    lat: 35.0055,
    lng: 135.7675,
    phone: '075-256-8210',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '新京極商店街核心', '錦市場旁'],
    notes: '京都最著名購物街新京極通內，錦市場走出來即達，旅客極度集中。'
  },
  {
    code: 'matsukiyo-kyoto-teramachi',
    name: '松本清 京都寺町通店',
    nameJa: 'マツモトキヨシ 寺町通店',
    region: '近畿',
    prefecture: '京都府',
    address: '京都府京都市中京区寺町通四条上る中之町561',
    lat: 35.0048,
    lng: 135.7668,
    phone: '075-254-7110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '寺町京極商店街', '老字號商圈'],
    notes: '寺町京極商店街南入口，古典拱廊街與現代藥妝完美結合。'
  },
  {
    code: 'matsukiyo-kyoto-porta',
    name: '松本清 京都站前 Porta 店',
    nameJa: 'マツモトキヨシ 京都ポルタ店',
    region: '近畿',
    prefecture: '京都府',
    address: '京都府京都市下京区烏丸通塩小路下る東塩小路町902',
    lat: 34.9858,
    lng: 135.7588,
    phone: '075-343-2615',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '京都站地下街直通', '新幹線旁'],
    notes: '京都站地下街 Porta 內，搭乘新幹線或 HARUKA 前補貨最便利。'
  },
  {
    code: 'matsukiyo-kyoto-hachijoguchi',
    name: '松本清 京都站八條口店',
    nameJa: 'マツモトキヨシ 京都駅八条口店',
    region: '近畿',
    prefecture: '京都府',
    address: '京都府京都市南区西九条北ノ内町300 近鉄名店街みやこみち',
    lat: 34.9835,
    lng: 135.7582,
    phone: '075-693-8110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '京都站八條口新幹線直通', 'Miyako Michi'],
    notes: '京都站南側八條口近鐵名店街內，前往飯店或搭近鐵奈良線超便利。'
  },
  {
    code: 'matsukiyo-kyoto-gion',
    name: '松本清 祇園店',
    nameJa: 'マツモトキヨシ 祇園八坂店',
    region: '近畿',
    prefecture: '京都府',
    address: '京都府京都市東山区祇園町北側281',
    lat: 35.0036,
    lng: 135.7765,
    phone: '075-533-7210',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '八坂神社西樓門前', '祇園花見小路旁'],
    notes: '祇園四條通正路上，八坂神社參道前，身穿和服觀光客必訪免稅門市。'
  },
  {
    code: 'matsukiyo-kyoto-arashiyama',
    name: '松本清 嵐山渡月橋店',
    nameJa: 'マツモトキヨシ 嵐山駅前店',
    region: '近畿',
    prefecture: '京都府',
    address: '京都府京都市右京区嵯峨天龍寺造路町20-2',
    lat: 35.0152,
    lng: 135.6775,
    phone: '075-873-3110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '京福嵐電嵐山站前', '渡月橋/竹林小徑'],
    notes: '嵐山天龍寺門前大街，嵐電嵐山站出站即達，觀光景點免稅專賣。'
  },

  // ==========================================
  // 4. 北海道 (札幌 / 小樽 / 函館 / 旭川)
  // ==========================================
  {
    code: 'matsukiyo-sapporo-tanukikoji-3chome',
    name: '松本清 札幌狸小路3丁目店',
    nameJa: 'マツモトキヨシ 札幌狸小路Part2店',
    region: '北海道・東北',
    prefecture: '北海道',
    address: '北海道札幌市中央区南2条西3丁目1-5',
    lat: 43.0575,
    lng: 141.3545,
    phone: '011-209-7030',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '狸小路商店街', '北海道藥妝伴手禮'],
    notes: '狸小路 3 丁目拱廊商店街內，馬油、保濕面膜與熱門藥品齊全。'
  },
  {
    code: 'matsukiyo-sapporo-tanukikoji-2chome',
    name: '松本清 札幌狸小路2丁目店',
    nameJa: 'マツモトキヨシ 札幌狸小路2丁目店',
    region: '北海道・東北',
    prefecture: '北海道',
    address: '北海道札幌市中央区南2条西2丁目4',
    lat: 43.0578,
    lng: 141.3548,
    phone: '011-219-5581',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '狸小路商店街', '大型旗艦店', '中文對應'],
    notes: '狸小路 2 丁目拱廊商店街內，全札幌規模最大、遊客必訪的松本清。'
  },
  {
    code: 'matsukiyo-sapporo-paseo',
    name: '松本清 札幌站地下街店',
    nameJa: 'マツモトキヨシ JR札幌駅店',
    region: '北海道・東北',
    prefecture: '北海道',
    address: '北海道札幌市北区北6条西4丁目3-1',
    lat: 43.0688,
    lng: 141.3508,
    phone: '011-213-5011',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '札幌站直通', '防雪地下道直連'],
    notes: 'JR 札幌站直結地下街，搭乘 JR 前後免出站即可輕鬆免稅購物。'
  },
  {
    code: 'matsukiyo-sapporo-susukino',
    name: '松本清 札幌薄野店',
    nameJa: 'マツモトキヨシ すすきの店',
    region: '北海道・東北',
    prefecture: '北海道',
    address: '北海道札幌市中央区南4条西3丁目1-1 COCONO SUSUKINO B1F',
    lat: 43.0555,
    lng: 141.3538,
    phone: '011-522-8110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '薄野地標商場COCONO', '深夜購物'],
    notes: '札幌夜生活核心薄野十字路口，COCONO SUSUKINO 地下 1 樓。'
  },
  {
    code: 'matsukiyo-chitose-domestic',
    name: '松本清 新千歲機場店',
    nameJa: 'マツモトキヨシ 新千歳空港店',
    region: '北海道・東北',
    prefecture: '北海道',
    address: '北海道千歳市美々 新千歳空港ターミナルビル 2F',
    lat: 42.7875,
    lng: 141.6812,
    phone: '0123-46-5110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '新千歲機場航廈2F', '離境前補貨'],
    notes: '新千歲機場航廈 2 樓出發大廳旁，搭機回台前最後採購熱門常備藥與美妝。'
  },
  {
    code: 'matsukiyo-otaru-sakaimachi',
    name: '松本清 小樽堺町通店',
    nameJa: 'マツモトキヨシ 小樽堺町通り店',
    region: '北海道・東北',
    prefecture: '北海道',
    address: '北海道小樽市堺町5-32',
    lat: 43.1935,
    lng: 141.0068,
    phone: '0134-31-8110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '小樽運河與音樂盒堂旁', '浪漫堺町通'],
    notes: '小樽堺町通商店街核心，鄰近北一硝子與小樽音樂盒堂。'
  },
  {
    code: 'matsukiyo-hakodate-ekimae',
    name: '松本清 函館站前店',
    nameJa: 'マツモトキヨシ ハコビバ函館駅前店',
    region: '北海道・東北',
    prefecture: '北海道',
    address: '北海道函館市若松町12-8 ハコビバ 1F',
    lat: 41.7725,
    lng: 140.7275,
    phone: '0138-24-3110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '函館站出站即達', 'HAKOVIVA商場'],
    notes: 'JR 函館站出站 1 分鐘，複合商場 HAKOVIVA 內，朝市與路面電車旁。'
  },
  {
    code: 'matsukiyo-hakodate-goryokaku',
    name: '松本清 函館五稜郭店',
    nameJa: 'マツモトキヨシ 丸井今井函館店',
    region: '北海道・東北',
    prefecture: '北海道',
    address: '北海道函館市本町32-15 丸井今井函館店 B1F',
    lat: 41.7915,
    lng: 140.7538,
    phone: '0138-32-1110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '五稜郭塔旁', '丸井今井百貨直通'],
    notes: '五稜郭繁華街中心，五稜郭公園參觀櫻花與星形城郭後免稅購物首選。'
  },
  {
    code: 'matsukiyo-asahikawa-kaimono',
    name: '松本清 旭川站前買物公園通店',
    nameJa: 'マツモトキヨシ 旭川平和通買物公園店',
    region: '北海道・東北',
    prefecture: '北海道',
    address: '北海道旭川市1条通7丁目',
    lat: 43.7662,
    lng: 142.3592,
    phone: '0166-29-3110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '旭川買物公園通', '富良野/美瑛玄關'],
    notes: '旭川平和通買物公園步行街起點，JR 旭川站出站 2 分鐘。'
  },

  // ==========================================
  // 5. 沖繩 (那霸 / 美國村 / 來客夢 / 豐崎)
  // ==========================================
  {
    code: 'matsukiyo-naha-kokusaidori-chuo',
    name: '松本清 那霸國際通中央店',
    nameJa: 'マツモトキヨシ 国際通り店',
    region: '九州・沖繩',
    prefecture: '沖繩縣',
    address: '沖縄県那覇市松尾2-8-16',
    lat: 26.2158,
    lng: 127.6888,
    phone: '098-860-2670',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '國際通核心', '防曬美白專區'],
    notes: '那霸國際通中心地帶，沖繩限定美妝、防曬與伴手禮專賣。'
  },
  {
    code: 'matsukiyo-naha-kokusai-matsuo',
    name: '松本清 那霸國際通松尾店',
    nameJa: 'マツモトキヨシ 那覇国際通り松尾店',
    region: '九州・沖繩',
    prefecture: '沖繩縣',
    address: '沖縄県那覇市松尾2-8-19',
    lat: 26.2142,
    lng: 127.6842,
    phone: '098-860-6181',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '國際通松尾交差點', '第一牧志公設市場旁'],
    notes: '國際通近縣廳前方向，周邊伴手禮與在地美食聚集。'
  },
  {
    code: 'matsukiyo-naha-kokusai-makishi',
    name: '松本清 那霸國際通牧志店',
    nameJa: 'マツモトキヨシ 那覇国際通り中央店',
    region: '九州・沖繩',
    prefecture: '沖繩縣',
    address: '沖縄県那覇市牧志2-1-1',
    lat: 26.2168,
    lng: 127.6875,
    phone: '098-860-9181',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '國際通大街', '沖繩必逛', '單軌牧志站旁'],
    notes: '那霸國際通正中心，沖繩旅行觀光客指名度最高藥妝店。'
  },
  {
    code: 'matsukiyo-naha-palette-kumoji',
    name: '松本清 縣廳前Palette久茂地店',
    nameJa: 'マツモトキヨシ パレットくもじ店',
    region: '九州・沖繩',
    prefecture: '沖繩縣',
    address: '沖縄県那覇市久茂地1-1-1 パレットくもじ 1F',
    lat: 26.2135,
    lng: 127.6802,
    phone: '098-867-1110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '單軌縣廳前站直達', '國際通入口'],
    notes: '單軌電車縣廳前站直通 Palette 久茂地百貨 1 樓，國際通起點。'
  },
  {
    code: 'matsukiyo-naha-shintoshin',
    name: '松本清 那霸新都心天久店',
    nameJa: 'マツモトキヨシ 天久りうぼう楽市店',
    region: '九州・沖繩',
    prefecture: '沖繩縣',
    address: '沖縄県那覇市天久1-2-1 樂市商場內',
    lat: 26.2325,
    lng: 127.6938,
    phone: '098-860-8110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '新都心樂市商場', '超大免費停車場', '沖繩自駕必訪'],
    notes: '那霸新都心天久琉球樂市商場內，鄰近大國藥妝、無印良品與大創。'
  },
  {
    code: 'matsukiyo-okinawa-american-village',
    name: '松本清 北谷美國村店',
    nameJa: 'マツモトキヨシ アメリカンビレッジ店',
    region: '九州・沖繩',
    prefecture: '沖繩縣',
    address: '沖縄県中頭郡北谷町美浜9-1 デポアイランド 1F',
    lat: 26.3165,
    lng: 127.7568,
    phone: '098-982-7110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '美國村Depot Island', '落日海灘旁', '自駕渡假商圈'],
    notes: '北谷美國村 Depot Island 內，夕陽海灘散策後最佳免稅購物點。'
  },
  {
    code: 'matsukiyo-okinawa-rycom',
    name: '松本清 沖繩永旺來客夢店',
    nameJa: 'マツモトキヨシ イオンモール沖縄ライカム店',
    region: '九州・沖繩',
    prefecture: '沖繩縣',
    address: '沖縄県中頭郡北中城村ライカム1番地 イオンモール沖縄ライカム 1F',
    lat: 26.3145,
    lng: 127.7952,
    phone: '098-931-9110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '永旺來客夢巨型商場', '沖繩中部自駕必逛'],
    notes: '沖繩最大購物中心 AEON Mall Rycom 1 樓，寬敞挑高，貨源超充足。'
  },
  {
    code: 'matsukiyo-okinawa-ashibinaa',
    name: '松本清 沖繩豐崎Outlet店',
    nameJa: 'マツモトキヨシ あしびなー店',
    region: '九州・沖繩',
    prefecture: '沖繩縣',
    address: '沖縄県豊見城市豊崎1-188 沖縄アウトレットモール あしびなー',
    lat: 26.1585,
    lng: 127.6575,
    phone: '098-851-2110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '沖繩Ashibinaa Outlet', '那霸機場15分'],
    notes: '沖繩 Ashibinaa Outlet 購物城內，還車或前往那霸機場前絕佳掃貨點。'
  },
  {
    code: 'matsukiyo-naha-airport',
    name: '松本清 那霸機場國際線店',
    nameJa: 'マツモトキヨシ 那覇空港国際線ターミナル店',
    region: '九州・沖繩',
    prefecture: '沖繩縣',
    address: '沖縄県那覇市字鏡水150 那覇空港 国際線エリア 3F',
    lat: 26.2065,
    lng: 127.6468,
    phone: '098-859-8110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '那霸機場國際線3F', '返台登機前最後採買'],
    notes: '那霸機場國際線 3 樓出境前大廳，過安檢前補齊免稅藥妝伴手禮。'
  },

  // ==========================================
  // 6. 九州 (福岡 / 熊本 / 鹿兒島 / 長崎 / 大分)
  // ==========================================
  {
    code: 'matsukiyo-hakata-chikagai',
    name: '松本清 博多站地下街店',
    nameJa: 'マツモトキヨシ 博多駅地下街店',
    region: '九州・沖繩',
    prefecture: '福岡縣',
    address: '福岡県福岡市博多区博多駅中央街1-1 地下1F',
    lat: 33.5902,
    lng: 130.4195,
    phone: '092-474-0610',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '博多車站地下街直通', '全天候不受天氣影響'],
    notes: 'JR 博多站中央地下街直通，免出站即可完成免稅採買。'
  },
  {
    code: 'matsukiyo-hakata-chikushiguchi',
    name: '松本清 博多站筑紫口店',
    nameJa: 'マツモトキヨシ 博多駅筑紫口店',
    region: '九州・沖繩',
    prefecture: '福岡縣',
    address: '福岡県福岡市博多区博多駅中央街4-23',
    lat: 33.5895,
    lng: 130.4215,
    phone: '092-432-8110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '新幹線筑紫口旁', '都飯店周邊'],
    notes: '新幹線筑紫口出站步行 1 分鐘，鄰近博多都酒店，搭新幹線極便利。'
  },
  {
    code: 'matsukiyo-fukuoka-tenjin-nishi',
    name: '松本清 福岡天神西通店',
    nameJa: 'マツモトキヨシ 福岡天神西通り店',
    region: '九州・沖繩',
    prefecture: '福岡縣',
    address: '福岡県福岡市中央区天神2-7-14',
    lat: 33.5898,
    lng: 130.3975,
    phone: '092-739-1181',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '天神西通潮流商圈', '深夜營業'],
    notes: '天神西通潮流一級戰區，營業至深夜 23:00，美妝與藥品庫存充足。'
  },
  {
    code: 'matsukiyo-fukuoka-tenjin-underground',
    name: '松本清 天神地下街店',
    nameJa: 'マツモトキヨシ 天神地下街店',
    region: '九州・沖繩',
    prefecture: '福岡縣',
    address: '福岡県福岡市中央区天神2丁目地下3号 天神地下街東2番街',
    lat: 33.5908,
    lng: 130.4005,
    phone: '092-738-3110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '天神地下街直結', '西鐵天神大牟田線直達'],
    notes: '全九州最奢華歐風天神地下街東 2 番街，逛街無懼日曬雨淋。'
  },
  {
    code: 'matsukiyo-hakata-canalcity',
    name: '松本清 博多運河城店',
    nameJa: 'マツモトキヨシ キャナルシティ博多店',
    region: '九州・沖繩',
    prefecture: '福岡縣',
    address: '福岡県福岡市博多区住吉1-2 キャナルシティ博多 B1F',
    lat: 33.5898,
    lng: 130.4108,
    phone: '092-263-2110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '博多運河城B1F', '水舞秀旁'],
    notes: '福岡人氣指標購物中心 Canal City 地下 1 樓，觀看水舞秀前後順逛。'
  },
  {
    code: 'matsukiyo-nakasu-kawabata',
    name: '松本清 中洲川端店',
    nameJa: 'マツモトキヨシ 中洲ゲイツ店',
    region: '九州・沖繩',
    prefecture: '福岡縣',
    address: '福岡県福岡市博多区中洲3-7-24 gate\'s 1F',
    lat: 33.5938,
    lng: 130.4065,
    phone: '092-283-7110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '中洲川端站直結', '24小時營業', '一蘭總本店旁'],
    notes: '地下鐵中洲川端站直通 gate\'s 大樓 1 樓，一蘭拉麵總本店對面，深夜營業。'
  },
  {
    code: 'matsukiyo-kumamoto-shimotori',
    name: '松本清 熊本下通中央店',
    nameJa: 'マツモトキヨシ 熊本下通中央店',
    region: '九州・沖繩',
    prefecture: '熊本縣',
    address: '熊本県熊本市中央区手取本町5-1',
    lat: 32.8028,
    lng: 130.7085,
    phone: '096-312-3310',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '下通拱廊商店街', '鶴屋百貨旁'],
    notes: '熊本最長拱廊商店街下通入口，鄰近通町筋路面電車站與鶴屋百貨。'
  },
  {
    code: 'matsukiyo-kumamoto-sakuramachi',
    name: '松本清 熊本櫻町Sakuramachi店',
    nameJa: 'マツモトキヨシ サクラマチ熊本店',
    region: '九州・沖繩',
    prefecture: '熊本縣',
    address: '熊本県熊本市中央区桜町3-10 SAKURA MACHI Kumamoto B1F',
    lat: 32.7995,
    lng: 130.7032,
    phone: '096-327-8110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '熊本櫻町巴士總站直結', '熊本熊廣場旁'],
    notes: '全九州最大巴士總站與 SAKURA MACHI 商場 B1F，自駕與搭車樞紐。'
  },
  {
    code: 'matsukiyo-kagoshima-tenmonkan',
    name: '松本清 鹿兒島天文館店',
    nameJa: 'マツモトキヨシ 鹿児島天文館店',
    region: '九州・沖繩',
    prefecture: '鹿兒島縣',
    address: '鹿児島県鹿児島市中町1-1',
    lat: 31.5912,
    lng: 130.5552,
    phone: '099-219-3180',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '天文館電車通', '南九州最大商圈'],
    notes: '鹿兒島最繁華的天文館通商店街入口，南九州藥妝免稅重鎮。'
  },
  {
    code: 'matsukiyo-kagoshima-chuo',
    name: '松本清 鹿兒島中央站AmuPlaza店',
    nameJa: 'マツモトキヨシ アミュプラザ鹿児島店',
    region: '九州・沖繩',
    prefecture: '鹿兒島縣',
    address: '鹿児島県鹿児島市中央町1-1 アミュプラザ鹿児島 本館 B1F',
    lat: 31.5835,
    lng: 130.5432,
    phone: '099-812-7110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '鹿兒島中央站直結', '九州新幹線起迄站'],
    notes: '九州新幹線起迄站鹿兒島中央站直結 AMU PLAZA 地下 1 樓。'
  },
  {
    code: 'matsukiyo-nagasaki-hamamachi',
    name: '松本清 長崎濱町中央店',
    nameJa: 'マツモトキヨシ 長崎浜町中央通り店',
    region: '九州・沖繩',
    prefecture: '長崎縣',
    address: '長崎県長崎市浜町7-11',
    lat: 32.7435,
    lng: 129.8785,
    phone: '095-818-8110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '長崎濱町拱廊街', '觀光通電車站旁'],
    notes: '長崎規模最大之濱町拱廊商店街中央，眼鏡橋與思案橋觀光必逛。'
  },
  {
    code: 'matsukiyo-nagasaki-ekimae',
    name: '松本清 長崎站AmuPlaza店',
    nameJa: 'マツモトキヨシ アミュプラザ長崎店',
    region: '九州・沖繩',
    prefecture: '長崎縣',
    address: '長崎県長崎市尾上町1-1 アミュプラザ長崎 本館 1F',
    lat: 32.7525,
    lng: 129.8705,
    phone: '095-808-1110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '西九州新幹線直通', '長崎站直達'],
    notes: '西九州新幹線長崎站直通 AMU PLAZA 1 樓，前往佐世保/福岡樞紐。'
  },
  {
    code: 'matsukiyo-beppu-ekimae',
    name: '松本清 別府站前店',
    nameJa: 'マツモトキヨシ 別府駅前通り店',
    region: '九州・沖繩',
    prefecture: '大分縣',
    address: '大分県別府市駅前町12-1',
    lat: 33.2795,
    lng: 131.5015,
    phone: '0977-27-8110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '別府車站東口', '別府溫泉巡禮'],
    notes: 'JR 別府站東口出站步行 1 分鐘，日本溫泉之鄉中心免稅門市。'
  },

  // ==========================================
  // 7. 中部東海 (名古屋 / 金澤 / 靜岡 / 輕井澤)
  // ==========================================
  {
    code: 'matsukiyo-nagoya-sakae',
    name: '松本清 名古屋榮店',
    nameJa: 'マツモトキヨシ 名古屋栄二丁目店',
    region: '中部',
    prefecture: '愛知縣',
    address: '愛知県名古屋市中区栄2-2-5',
    lat: 35.1685,
    lng: 136.9035,
    phone: '052-229-8110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '榮商圈廣小路通', '名古屋核心'],
    notes: '名古屋市區最繁華的榮商圈廣小路通，鄰近各大百貨公司。'
  },
  {
    code: 'matsukiyo-nagoya-sakae-mori',
    name: '松本清 名古屋榮地下街店',
    nameJa: 'マツモトキヨシ 栄森の地下街店',
    region: '中部',
    prefecture: '愛知縣',
    address: '愛知県名古屋市中区栄3-5-12 森の地下街',
    lat: 35.1698,
    lng: 136.9085,
    phone: '052-953-6110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '榮地下街中央通', '綠洲21旁'],
    notes: '榮站直結森之地下街，鄰近綠洲 21 (Oasis 21) 與中部電力電視塔。'
  },
  {
    code: 'matsukiyo-nagoya-meieki-taiko',
    name: '松本清 名驛太閤通口店',
    nameJa: 'マツモトキヨシ 名駅太閤通口店',
    region: '中部',
    prefecture: '愛知縣',
    address: '愛知県名古屋市中村区椿町6-9',
    lat: 35.1702,
    lng: 136.8808,
    phone: '052-459-3180',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '名古屋站新幹線口', 'BicCamera對面'],
    notes: 'JR 名古屋站太閤通口（新幹線口）出站即達，Bic Camera 對角。'
  },
  {
    code: 'matsukiyo-nagoya-meitetsu',
    name: '松本清 名古屋站名鐵百貨店',
    nameJa: 'マツモトキヨシ 名鉄百貨店本店',
    region: '中部',
    prefecture: '愛知縣',
    address: '愛知県名古屋市中村区名駅1-2-1 名鉄百貨店 メンズ館 B1F',
    lat: 35.1688,
    lng: 136.8845,
    phone: '052-585-7110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '名鐵巨大人形Nana醬旁', '中部機場特急改札直達'],
    notes: '名鐵百貨 B1F，名鐵特急 μ-SKY 前往中部國際機場必經之路。'
  },
  {
    code: 'matsukiyo-nagoya-osu',
    name: '松本清 名古屋大須仁王門通店',
    nameJa: 'マツモトキヨシ 大須仁王門通り店',
    region: '中部',
    prefecture: '愛知縣',
    address: '愛知県名古屋市中区大須2-18-28',
    lat: 35.1592,
    lng: 136.8995,
    phone: '052-220-3110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '大須商店街', '大須觀音寺旁'],
    notes: '大須觀音寺參道仁王門通商店街內，名古屋最熱鬧的次文化與古町街區。'
  },
  {
    code: 'matsukiyo-centrair',
    name: '松本清 中部國際機場店',
    nameJa: 'マツモトキヨシ セントレア店',
    region: '中部',
    prefecture: '愛知縣',
    address: '愛知県常滑市セントレア1-1 第1ターミナル 3F',
    lat: 34.8585,
    lng: 136.8152,
    phone: '0569-38-8110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '中部國際機場3F', '離境登機前'],
    notes: '中部國際機場新特麗亞第 1 航廈 3 樓出發大廳，離境前最後免稅店。'
  },
  {
    code: 'matsukiyo-shizuoka-ekimae',
    name: '松本清 靜岡站前店',
    nameJa: 'マツモトキヨシ パルシェ静岡駅店',
    region: '中部',
    prefecture: '靜岡縣',
    address: '静岡県静岡市葵区黒金町49 パルシェ食彩館 1F',
    lat: 34.9715,
    lng: 138.3892,
    phone: '054-273-8110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', 'JR靜岡站直通', 'PARCHE商場'],
    notes: 'JR 靜岡站直通 PARCHE 食彩館 1 樓，富士山觀光玄關免稅門市。'
  },
  {
    code: 'matsukiyo-hamamatsu-ekimae',
    name: '松本清 濱松站前MAY-ONE店',
    nameJa: 'マツモトキヨシ メイワン浜松駅店',
    region: '中部',
    prefecture: '靜岡縣',
    address: '静岡県浜松市中区砂山町6-1 メイワン エキマチ 1F',
    lat: 34.7038,
    lng: 137.7345,
    phone: '053-457-3110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', 'JR濱松站直結', '新幹線停靠站'],
    notes: 'JR 濱松站共構商場 MAY-ONE 1 樓，東海道新幹線旅客中繼站。'
  },
  {
    code: 'matsukiyo-karuizawa-ekimae',
    name: '松本清 輕井澤站前店',
    nameJa: 'マツモトキヨシ 軽井沢駅前店',
    region: '中部',
    prefecture: '長野縣',
    address: '長野県北佐久郡軽井沢町軽井沢1178-1',
    lat: 36.3432,
    lng: 138.6355,
    phone: '0267-41-2180',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '輕井澤站北口', '渡假避暑首選'],
    notes: '北陸新幹線輕井澤站北口步行 2 分鐘，前進雲場池與舊輕井澤必經。'
  },
  {
    code: 'matsukiyo-nagano-ekimae',
    name: '松本清 長野站善光寺口店',
    nameJa: 'マツモトキヨシ MIDORI長野店',
    region: '中部',
    prefecture: '長野縣',
    address: '長野県長野市南千歳1-22-6 MIDORI長野 1F',
    lat: 36.6432,
    lng: 138.1888,
    phone: '026-224-1110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '長野站直結MIDORI', '善光寺參拜參道'],
    notes: 'JR 長野站共構 MIDORI 商場 1 樓，前往善光寺與地獄谷野猿公苑前哨站。'
  },
  {
    code: 'matsukiyo-kanazawa-ekimae',
    name: '松本清 金澤站西口店',
    nameJa: 'マツモトキヨシ 金沢駅西口店',
    region: '中部',
    prefecture: '石川縣',
    address: '石川県金沢市広岡1-9-1',
    lat: 36.5795,
    lng: 136.6475,
    phone: '076-260-8110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '金澤站西口出站即達', '金澤鼓門旁'],
    notes: 'JR 金澤站西口出站 1 分鐘，北陸新幹線重要交通樞紐。'
  },
  {
    code: 'matsukiyo-kanazawa-rinto',
    name: '松本清 金澤站Rinto店',
    nameJa: 'マツモトキヨシ 金沢百番街Rinto店',
    region: '中部',
    prefecture: '石川縣',
    address: '石川県金沢市木ノ新保町1-1 金沢百番街 Rinto 1F',
    lat: 36.5782,
    lng: 136.6488,
    phone: '076-260-3180',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '金澤百番街直通', '車站商場內'],
    notes: '金澤站百番街 Rinto 購物中心內，免出站即可輕鬆選購免稅美妝。'
  },
  {
    code: 'matsukiyo-kanazawa-korinbo',
    name: '松本清 金澤香林坊店',
    nameJa: 'マツモトキヨシ 香林坊アトリオ店',
    region: '中部',
    prefecture: '石川縣',
    address: '石川県金沢市香林坊1-1-1 香林坊アトリオ B1F',
    lat: 36.5622,
    lng: 136.6538,
    phone: '076-220-1110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '金澤兼六園旁', '香林坊百貨商圈'],
    notes: '金澤名勝兼六園與金澤 21 世紀美術館旁，香林坊 Atrio 百貨地下 1 樓。'
  },
  {
    code: 'matsukiyo-toyama-ekimae',
    name: '松本清 富山站前Marier店',
    nameJa: 'マツモトキヨシ マリエとやま店',
    region: '中部',
    prefecture: '富山縣',
    address: '富山県富山市桜町1-1-61 マリエとやま 1F',
    lat: 36.7012,
    lng: 137.2138,
    phone: '076-445-3110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '富山站南口直通', '立山黑部玄關'],
    notes: 'JR 富山站直結 MARIER 百貨 1 樓，立山黑部阿爾卑斯路線玄關口。'
  },

  // ==========================================
  // 8. 中國・四國 (廣島 / 岡山 / 高松 / 松山)
  // ==========================================
  {
    code: 'matsukiyo-hiroshima-hondori',
    name: '松本清 廣島本通中央店',
    nameJa: 'マツモトキヨシ 広島本通中央店',
    region: '中國・四國',
    prefecture: '廣島縣',
    address: '広島県広島市中区本通3-10',
    lat: 34.3928,
    lng: 132.4585,
    phone: '082-545-5681',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '廣島本通商店街', '和平紀念公園旁'],
    notes: '廣島本通商店街正中心，廣島最大型松本清免稅專門店。'
  },
  {
    code: 'matsukiyo-hiroshima-ekie',
    name: '松本清 廣島站ekie店',
    nameJa: 'マツモトキヨシ ekie広島店',
    region: '中國・四國',
    prefecture: '廣島縣',
    address: '広島県広島市南区松原町1-2 ekie WEST 1F',
    lat: 34.3975,
    lng: 132.4752,
    phone: '082-263-1110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', 'JR廣島站直結', '新幹線北口直通'],
    notes: '廣島站共構 ekie 購物商場 1 樓，轉乘新幹線或前往宮島前絕佳補給點。'
  },
  {
    code: 'matsukiyo-okayama-ekimae-matsu',
    name: '松本清 岡山站前店',
    nameJa: 'マツモトキヨシ 岡山駅前店',
    region: '中國・四國',
    prefecture: '岡山縣',
    address: '岡山県岡山市北区駅前町1-8-18',
    lat: 34.6652,
    lng: 133.9212,
    phone: '086-235-5181',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '岡山站東口直達', 'ICOT NICOT旁'],
    notes: 'JR 岡山站東口出站步行 2 分鐘，山陽新幹線交通樞紐核心店。'
  },
  {
    code: 'matsukiyo-okayama-ichibangai',
    name: '松本清 岡山一番街地下街店',
    nameJa: 'マツモトキヨシ 岡山一番街店',
    region: '中國・四國',
    prefecture: '岡山縣',
    address: '岡山県岡山市北区駅元町一番街地下',
    lat: 34.6658,
    lng: 133.9188,
    phone: '086-224-8110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '岡山站地下街直結', '避雨地下商圈'],
    notes: '岡山一番街地下商場內，直達岡山高島屋與永旺夢樂城岡山。'
  },
  {
    code: 'matsukiyo-takamatsu-marugamemachi',
    name: '松本清 高松丸龜町店',
    nameJa: 'マツモトキヨシ 高松丸亀町店',
    region: '中國・四國',
    prefecture: '香川縣',
    address: '香川県高松市丸亀町7-16 丸亀町グリーン',
    lat: 34.3418,
    lng: 134.0505,
    phone: '087-811-6681',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '丸龜町GREEN商場', '四國核心商圈'],
    notes: '高松丸龜町 GREEN 商場 1 樓，四國最時髦拱廊購物街指標店。'
  },
  {
    code: 'matsukiyo-matsuyama-okaido',
    name: '松本清 松山大街道店',
    nameJa: 'マツモトキヨシ 松山大街道中央店',
    region: '中國・四國',
    prefecture: '愛媛縣',
    address: '愛媛県松山市大街道2-3-5',
    lat: 33.8402,
    lng: 132.7695,
    phone: '089-913-7110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '大街道商店街', '松山城纜車道入口'],
    notes: '松山最熱鬧的大街道拱廊內，道後溫泉與松山城觀光客必訪門市。'
  },

  // ==========================================
  // 9. 東北 (仙台 / 青森 / 盛岡)
  // ==========================================
  {
    code: 'matsukiyo-sendai-chuo',
    name: '松本清 仙台中央通店',
    nameJa: 'マツモトキヨシ 仙台中央通り店',
    region: '北海道・東北',
    prefecture: '宮城縣',
    address: '宮城県仙台市青葉区中央2-5-5',
    lat: 38.2612,
    lng: 140.8758,
    phone: '022-263-8180',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '克里斯羅德商店街', '東北最大繁華街'],
    notes: '仙台 Chris Road 拱廊商店街中央，東北地區美妝藥妝最大免稅旗艦店。'
  },
  {
    code: 'matsukiyo-sendai-ichibancho',
    name: '松本清 仙台一番町店',
    nameJa: 'マツモトキヨシ 仙台一番町店',
    region: '北海道・東北',
    prefecture: '宮城縣',
    address: '宮城県仙台市青葉区一番町4-3-22',
    lat: 38.2625,
    lng: 140.8715,
    phone: '022-716-6081',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', '一番町Vlandome商店街', '東北核心繁華街'],
    notes: '仙台一番町拱廊商店街核心，東北最大藥妝聚集點。'
  },
  {
    code: 'matsukiyo-morioka-ekimae',
    name: '松本清 盛岡站前FES"AN店',
    nameJa: 'マツモトキヨシ フェザン盛岡店',
    region: '北海道・東北',
    prefecture: '岩手縣',
    address: '岩手県盛岡市盛岡駅前通1-44 盛岡駅ビル フェザン B1F',
    lat: 39.7015,
    lng: 141.1362,
    phone: '019-654-8110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', 'JR盛岡站直結', '秋田/東北新幹線樞紐'],
    notes: 'JR 盛岡站 FES"AN 購物中心 B1F，前往青森、秋田新幹線交會點。'
  },
  {
    code: 'matsukiyo-aomori-ekimae',
    name: '松本清 青森站前LOVINA店',
    nameJa: 'マツモトキヨシ ラビナ青森店',
    region: '北海道・東北',
    prefecture: '青森縣',
    address: '青森県青森市柳川1-2-3 ラビナ 1F',
    lat: 40.8295,
    lng: 140.7342,
    phone: '017-732-3110',
    url: 'https://www.matsukiyococokara-online.com/',
    tags: ['免稅 (Tax-Free)', 'JR青森站東口直達', 'LOVINA商場'],
    notes: 'JR 青森站共構 LOVINA 商場 1 樓，睡魔之家 WARASSE 與八甲田丸旁。'
  }
];

/**
 * 建置標準化松本清門市資料集
 * @param {Array<object>} [rawList=MATSUKIYO_STORES_SEED] 
 * @param {Array<object>} [stationsList=[]] 
 * @returns {Array<object>}
 */
export function buildMatsukiyoStores(rawList = MATSUKIYO_STORES_SEED, stationsList = []) {
  const result = [];

  for (const s of rawList) {
    const lat = Number(s.lat);
    const lng = Number(s.lng);
    const id = s.id || `matsukiyo-${s.code || Math.random().toString(36).slice(2, 8)}`;

    const stationMatch = findNearestStation(lat, lng, stationsList);
    const stationName = stationMatch.station ? stationMatch.station.name : '鄰近車站';
    const walkMin = stationMatch.walkMinutes || 3;

    let tags = [];
    if (Array.isArray(s.tags)) {
      tags = [...s.tags];
    } else if (typeof s.tags === 'string') {
      tags = s.tags.split(',').map(t => t.trim()).filter(Boolean);
    }

    if (!tags.includes('免稅 (Tax-Free)')) {
      tags.unshift('免稅 (Tax-Free)');
    }
    if (walkMin <= 3 && !tags.includes('車站步行3分內')) {
      tags.push('車站步行3分內');
    }

    const bookingUrl = s.url || s.bookingUrl || 'https://www.matsukiyococokara-online.com/';
    const imageUrl = s.imageUrl || 'https://images.unsplash.com/photo-1586015555751-63bb77f4322a?auto=format&fit=crop&w=800&q=80';

    result.push({
      id,
      category: '購物藥妝',
      brand: '松本清',
      name: s.name,
      nameJa: s.nameJa || s.name,
      region: s.region,
      prefecture: s.prefecture,
      nearestStation: stationName,
      stationLine: stationMatch.station?.lines?.[0] || 'JR / 地鐵',
      stationAccess: stationMatch.note || `鄰近 ${stationName} 步行約 ${walkMin} 分鐘`,
      walkMinutes: walkMin,
      address: s.address,
      coordinates: `${lat}, ${lng}`,
      lat,
      lng,
      phone: s.phone || '',
      bookingUrl,
      googleMapUrl: `https://maps.google.com/?q=${lat},${lng}`,
      imageUrl,
      images: [imageUrl],
      tags: tags.join(', '),
      notes: s.notes || '日本大型知名連鎖藥妝店，提供免稅服務與豐富的美妝保養品。'
    });
  }

  const { uniqueSpots, duplicateCount } = deduplicateSpots(result);
  const validation = validateSpotsBatch(uniqueSpots);
  console.log(`[Matsukiyo Scraper] 建置完成: 共 ${uniqueSpots.length} 間，去重: ${duplicateCount} 筆，有效通過: ${validation.validCount} 間`);

  return uniqueSpots;
}
